### ISSUE TITLE
codecov: file preview not working

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1026]
Summary: file previews such as [this](https://codecov.io/gh/Kong/kubernetes-ingress-controller/src/main/internal/ingress/controller/parser/parser.go) don't show line coverage.

Reproduction steps:
1. Navigate your web browser to https://codecov.io/gh/Kong/kubernetes-ingress-controller/
2. Click on any `*.go` file in the directory structure (with an intention to view line coverage), for example [this one](https://codecov.io/gh/Kong/kubernetes-ingress-controller/src/main/cli/ingress-controller/util.go)
3. Observe the following error instead of line coverage:
    > GitHub API: Forbidden 
    > 
    > Is the path cli/ingress-controller/util.go a relative path in your repository?
    > Learn how to apply path fixes in your configuration.
    > Please contact support for questions. 

xref #835

**Comment by shaneutt** [comment]
I did not get any API errors and in fact file previews were working for me. I believe the problem was due to the permissions in code coverage users for our github org.
I've activated you as a user @mflendrich, let me know if things are working properly now? If not please re-open and let's take another look :+1:
