### ISSUE TITLE
Multiple workspaces configuration with declarative YAML

### ISSUE THREAD

**Issue by mishkakipi** [Kong/kubernetes-ingress-controller#1058]
Hello,

Managing Kong via the manager, we can group our configs into workspaces.
When managing via declarative Yaml configurations all configs are shown under default workspace and it is a mess.

What would be the correct enabled/disabled components (proxy,manager,admin,ingress) combination to achieve the following-
Have all configs in all my workspaces shown under the same manager, managed under the same adminapi, processed by the same proxy, in a single Kubernetes namespace.

Thanks,
Michael.

**Comment by rainest** [comment]
The controller currently only supports a single workspace. We're exploring ways to rework this in the future, but for now, you'll want to deploy multiple controller-only Deployments, each configured to use a separate workspace, and a single Kong Deployment.

Since the controllers will no longer be inside the Kong Deployment, you'll need to also configure the admin API location. https://github.com/Kong/charts/tree/kong-1.15.0/charts/kong#standalone-controller-nodes covers all the settings needed.

That's geared towards our Helm chart, though the same general principles applies if you're not using it. Most of the settings are just [environment variables](), so if you're not using the chart, `ingressController.env.kong_admin_url` would instead be a `CONTROLLER_KONG_ADMIN_URL` environment variable. `CONTROLLER_INGRESS_CLASS` the non-chart equivalent of `ingressController.ingressClass`

I'll go ahead and close this out, but if you still have additional questions, please respond back and we'll reopen it.
