### ISSUE TITLE
Targeting Services with UDPIngress

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1080]
In our [original POC of UDPIngress](https://github.com/Kong/kubernetes-ingress-controller/pull/1057) we did not implement support for automated Kubernetes service resolution, instead requiring an explicit and manual configuration of the `Host` in the spec for that iteration.

The purpose of this issue is to add automated service resolution to UDP that would allow aliases and shorthand declaration of internal Kubernetes `Services` in the object spec that would be automatically configured, similar to what we do for other ingress APIs.

Acceptance Criteria:
- [ ] make it possible to configure service backends in `UDPIngress`
- [ ] establish integration tests for UDPIngress Service backends
- [ ] ensure integration tests work against DBLESS and Postgres DBMODE backend proxies (v1alpha1 did not support postgres due to problems with go-kong/deck when there's no k8sservice in dbmode)
- [ ] ~deploy `v1beta1.UDPIngress`~ update the UDPIngress schema appropriately (if it involves breaking changes, make it a new API version)
- [ ] remove `v1alpha1.UDPIngress`

**Comment by rainest** [comment]
Well, good news is that #1076 isn't really a hurdle here, since we should always set `service.host` and `service.port` directly, and don't need to ever use the URL shorthand.

A spike on the existing code, however, surfaces a number of challenges. tl;dr our existing types and upstream types rely on an assumption that everything is TCP at the K8S level, because it is. We also have apparently inconsistent Kong service naming depending on the type that spawns the Kong route+service combo. 

**Services can have both UDP and TCP ports with the same port integer**

We use only Name+Namespace+Port in our Kong service and upstream names throughout existing types:

```
// Kong service name
fmt.Sprintf("%s.%s.%d", ingress.Namespace, rule.Backend.ServiceName, rule.Backend.ServicePort)
// Upstream name
fmt.Sprintf("%s.%s.%d.svc", rule.Backend.ServiceName, ingress.Namespace, rule.Backend.ServicePort))
```

This isn't compatible with Services that use both transport protocols on the same integer port:

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
    - protocol: UDP
      port: 80
      targetPort: 9376
```

With UDP, this naming scheme will attempt to create two Kong services with the same name, sort of: the way that we use the service map means that we'll actually create one or the other first, and then attempt to attach a route to a service that doesn't match its protocol.

Upstreams don't care about protocol, though we may want to separate them for other reasons (different algorithm settings? idk).

TCPIngress didn't care about this since the underlying Service has `protocol: TCP` for either HTTP or TCP, and thus they couldn't really share a port.

**Varied backend port handling**

Our existing types vary in the types of ports they can support. Ingresses handle [either named or numbered ports](https://github.com/kubernetes/api/blob/v0.20.4/networking/v1/types.go#L441-L462), whereas TCPIngress has a simplified backend type that [only handles numbered ports](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.1.1/pkg/apis/configuration/v1beta1/types.go#L96-L103).

We build a `PortDef` struct that indicates what it's trying to use, either with [helper functions](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.1.1/internal/ingress/controller/parser/translate.go#L555-L571) or by [constructing the struct in place](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.1.1/internal/ingress/controller/parser/translate.go#L386)

Our existing helper doesn't handle protocol though, since it only takes in a [ServiceBackendPort](https://github.com/kubernetes/api/blob/v0.20.4/networking/v1/types.go#L451-L462) which, being designed for Ingress, doesn't care, because it can sort of assume that it's always TCP (it can't actually--the same sort of problem Service shown above would still be an issue, but apparently that didn't come up in the wild).

This matters in `findPort()`, which uses [different cases](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.1.1/internal/ingress/controller/parser/parser.go#L153-L198) to handle the various port types. Both named and numbered non-implicit ports will need support for protocol matching also.

**Varied service naming**
While our convention is to use the backend Service port integer for naming, there's inconsistency here also. Ingress v1beta1 used an `IntOrString`, so it'd apparently [get the port name](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.1.1/internal/ingress/controller/parser/translate.go#L81-L83) if that's what you used.

Ingress v1 splits those fields, so you apparently [get the number if set](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.1.1/internal/ingress/controller/parser/translate.go#L231-L232), or nothing otherwise.

TCPIngress always uses the number because it's simple and supports only that.

**Reviewing Gateway API types**

Looking forward to the future to see what this may require, since why not.

Both [UDPRouteRule](https://gateway-api.sigs.k8s.io/spec/#networking.x-k8s.io/v1alpha1.UDPRouteRule) and [TCPRouteRule](https://gateway-api.sigs.k8s.io/spec/#networking.x-k8s.io/v1alpha1.TCPRouteRule) use [RouteForwardTo](https://gateway-api.sigs.k8s.io/spec/#networking.x-k8s.io/v1alpha1.RouteForwardTo) to indicate where their upstream traffic goes. It has no protocol field, though it does mention:

> The protocol to use is defined using AppProtocol field (introduced in Kubernetes 1.18) in the Service resource.

This seems a bit odd since that (and the Protocol field) is a property of the [ServicePort](https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#serviceport-v1-core), not the entire Service.

You can reasonably infer what the protocol should be given the route type, but it doesn't look like the successor of ServiceBackend would provide more info than we have currently.

**Comment by shaneutt** [comment]
solving this in tandem with https://github.com/Kong/kubernetes-ingress-controller/issues/1081
