### ISSUE TITLE
KIC 2.0 - Making all user-facing Kubernetes APIs optional

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1089]
As a follow up to [KEP5](https://github.com/Kong/keps/pull/15) the purpose of this issue is to implement an analog to [upstream feature gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) in the KIC such as to make all user-facing Kubernetes APIs optional, and to improve communication with our end-users and community on the maturity and longevity of the APIs we maintain going forward.

Acceptance Criteria
- [x] feature gate functionality added to KIC, all `v1alpha*` APIs disabled by default
- [ ] ~living documentation for tracking our API's maturity and lifespan going forward in the form of a [version table](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features)~ moved to https://github.com/Kong/kubernetes-ingress-controller/issues/1095

**Comment by mflendrich** [comment]
This issue describes a scope of "feature gates" that seems quite broad and I'd like to be careful here, so that we don't jump into a "silver bullet" solution to feature gating from get-go. This is because for various classes of problems that we might want feature gates for, there are multiple levels on which those feature gates can be implemented: CLI flags for KIC, fields on the `IngressClass` resource, annotations/fields on Kubernetes resources, etc. If we don't start minimal (with a minimal domain of problems we're implementing feature gating for) we risk getting locked into a suboptimal solution to future problems.

In more concrete terms:
It seems to me that today we need feature gates only to enable or disable Kubernetes APIs to be watched (and, hence, to enable/disable an appropriate input controller). Would it make sense to restrict the scope of this issue only to this well-defined problem?

**Comment by mflendrich** [comment]
> Does that track? do we need to improve the language here?

Would summarizing this issue as "Making all user-facing Kubernetes APIs optional" rather than "Feature Gates" be acceptable? That would solve any misalignment here once and for all.

**Comment by mflendrich** [comment]
Closed by #1185
