### ISSUE TITLE
ExternalName not working

### ISSUE THREAD

**Issue by frenchf99** [Kong/kubernetes-ingress-controller#1098]
---
# Source: external-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: external-service
  annotations:
    configuration.konghq.com: sample-customization
  labels:
    helm.sh/chart: external-service-0.0.1
    app.kubernetes.io/name: external-service
    app.kubernetes.io/instance: external-service
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ExternalName
  ports:
    - port: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: external-service
    app.kubernetes.io/instance: external-service
  externalName: ****.execute-api.eu-west-2.amazonaws.com
---
# Source: external-service/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: external-service
  labels:
    helm.sh/chart: external-service-0.0.1
    app.kubernetes.io/name: external-service
    app.kubernetes.io/instance: external-service
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    konghq.com/override: sample-customization
    kubernetes.io/ingress.class: kong
    kubernetes.io/ingress.global-static-ip-name: platform
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: "***.***.com"
      http:
        paths:
          - path: /test/helloworld
            backend:
              serviceName: external-service
              servicePort: 443
---
# Source: external-service/templates/kongingress.yaml
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: sample-customization
proxy:
  protocol: https
route:
  protocols:
  - https
  strip_path: false

kong-ingress-controller:0.9.1

With an externalName of httpbin.org everything works as expected.

If I change the name to dynamically created hostname in AWS I get 403 or GCP I get 404.

I think this has something to do with not resolving the hostname correctly but cannot prove it.

Both endpoints in AWS and GCP are public and work when used directly.

**Comment by rainest** [comment]
A 4XX response indicates this isn't a DNS resolution issue. Kong returns a 503 for resolution failures.

While Kong can emit its own 404 responses (if the request did not match any route) or 403 responses (if an authentication plugin denied a request), those would come back regardless of the specific hostname in the ExternalName service: you'd still see them even when the Service was configured to point to httpbin if Kong was generating those responses on its own.

The information provided so far indicates that those requests are at least making it upstream to the AWS/GCP hosts, so if you're seeing a different response when sending requests to them without Kong, comparing access logs for those requests and the Kong requests could help indicate how the requests differ, which should help clarify what you'd need to change in your Kong configuration.

While it's hard to say what the cause of the issue is without access logs to compare, my best initial guess is the request hostname. [preserve-host](https://docs.konghq.com/kubernetes-ingress-controller/1.2.x/references/annotations/#konghqcompreserve-host) is `false` by default, so the upstream request will send the AWS/GCP hostname. If those hosts are configured to only respond to requests for the external hostname (i.e. the hostname that you use in your Ingress rule), that'd explain the issue, and setting that annotation to `true` would resolve it.
