### ISSUE TITLE
Support EndpointSlice

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1172]
In Kubernetes 1.21 ([release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#v1210), [KEP](https://github.com/freehan/enhancements/blob/master/keps/sig-network/20190603-EndpointSlice-API.md)), `EndpointSlice` graduated to GA (GV: `discovery.k8s.io/v1`), as a replacement for `core/v1` `Endpoint`.

This means that KIC can use the following APIs to watch service endpoints:
- `core/v1` `Endpoint`: all versions, with limitations, likely deprecated in the future
- `discovery.k8s.io/v1beta1`: k8s 1.18-1.24 (in 1.17 behind a feature gate)
- `discovery.k8s.io/v1`: k8s 1.21+

**Comment by shaneutt** [comment]
Closing as stale, if anyone is still in need of this support please feel free to comment here with your use cases and we'll be happy to re-open and re-assess.

**Comment by seh** [comment]
Does that mean that Kong still does not support _EndpointSlice_?

**Comment by shaneutt** [comment]
That's correct today, but this being _closed_ does not mean it's dead it just means it's not an active priority at this very moment. It will be our intention to open this again when this becomes a technical blocker or requirement, or sooner if there's a strong need.

**Comment by rainest** [comment]
Reopening this as an overly aggressive stale close. We had clear interest in this based on the earlier PRs and comments here, and got another from @pgold30 with new info as of 1.22, where this is more of a requirement with the endpoint cap.

---

### Discussed in https://github.com/Kong/kong/discussions/10616

<div type='discussions-op-text'>

<sup>Originally posted by **pgold30** April  5, 2023</sup>
Description:
EndpointSlice is now enabled by default in Kubernetes and offers some solid performance benefits for clusters with large Endpoint sets. It might be worthwhile to support consuming EndpointSlice, at least as optional.

Envoy is designed for scale and the use case for endpointslice also.

The lack of EndpointSlices implementation is unfortunately impacting production for us now. Since Kubernetes v1.22, Services that exceed 1000 Pods/network endpoints, Endpoints are now being truncated to a maximum of 1000 items.
Im sure thttps://github.com/kubernetes/ingress-nginx/issues/6017#issuecomment-1170285796 are many other people with the same issue. (same here in Countour)

Outlining the pieces needed to implement this issue @arkodg pointed https://github.com/envoyproxy/gateway/issues/35#issuecomment-1387344863

[Relevant Links:]
https://github.com/projectcontour/contour/issues/2696.
This was shortly discussed https://github.com/envoyproxy/gateway/issues/35 and https://github.com/envoyproxy/gateway/issues/35#issuecomment-1396422011
This was fixed on Feb 15 for nginx-ingress https://github.com/kubernetes/ingress-nginx/pull/8890</div>

**Comment by mflendrich** [comment]
Superseded by https://github.com/Kong/kubernetes-ingress-controller/issues/3916
