### ISSUE TITLE
TCPIngress Tests

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1179]
# TCPIngress Tests

The purpose of this issue is to ensure that we provide robust unit and integration test coverage of our `TCPIngress` API and relevant controller(s).

# Acceptance Criteria

Integration and unit tests must cover the below checklists for this issue to be considered resolved, each checklist item should be a test case in Go.

Rule Of Thumb: default to unit tests where feasible, and fallback to integration tests when the functionality being tested makes more contextual sense to test in a fully functional Kubernetes cluster.

## Validation Tests

- [x] several valid permutations of each available field in the `TCPIngress` API spec are covered
- [x] several invalid permutations of each available field in the `TCPIngress` API spec are covered

## General Functionality Tests

- [x] `TCPIngress` resources can be created and route properly to the relevant `Service`, the route becomes available in under 1 minute
- [x] `TCPIngress` resources can be updated for a new backend `Service`, the routes change properly in under 1 minute
- [x] When `TCPIngress` spec changes, the behavior of persistent connections is tested (backend specific)
- [ ] When `TCPIngress` spec changes, repeated parallel transient connections to the backend show no failures.
- [ ] Long running persistent connections (where the backend server doesn't support reconnect mechanisms) disconnect and fail properly when pods change
- [x] `TCPIngress` resources can be deleted and the backend route is disconnected in under 1 minute

## Status Tests

- [x] `TCPIngress` status is checked for consistent `LoadBalancer` state between creation and multiple updates to the spec

## Specific Functionality Tests

- [x] `TCPIngress` ingress TLS configuration
- [x] `TCPIngress` ingress TLS configuration for multiple hosts

## Performance Tests

- [ ] Multiple `TCPIngress` resources can be rapidly created, each backend resolving in under 1 minute
- [ ] Bulk parallel connections through `TCPIngress` succeed, no failures at KIC/Kong level
- [ ] Multiple `TCPIngress` resources can be rapidly deleted, each backend route becomes disconnected in under 1 minute

**Comment by mflendrich** [comment]
This requires validation - the existing integration test may cover some of the scope.

**Comment by rainest** [comment]
> several valid permutations of each available field in the TCPIngress API spec are covered
> several invalid permutations of each available field in the TCPIngress API spec are covered

https://github.com/Kong/kubernetes-ingress-controller/blob/d4a6ecb8f8e027be79937423b0c0badaf39646e7/internal/parser/translate_test.go#L713-L847 has general parse tests for all positive cases, but no negative cases

> TCPIngress resources can be created and route properly to the relevant Service, the route becomes available in under 1 minute

https://github.com/Kong/kubernetes-ingress-controller/blob/d4a6ecb8f8e027be79937423b0c0badaf39646e7/test/integration/tcpingress_test.go#L118-L137 we use the same `ingressWait` 5-minute time limit for most tests.

The remainder is almost entirely Kong proxy behavior (beyond that we make changes to proxy config when asked). Manual testing against Kong shows that:

- Once a TCP connection is routed, it remains routed: you can update the route that handled it, even to remove the criteria that originally included it, and packets through that connection will still go to their original destination using the same connection, for both port- and SNI-based routes.
- A dead upstream (in this case, killing a netstat listen) will normally close the upstream connection however and FIN the downstream client.

>  TCPIngress resources can be updated for a new backend Service, the routes change properly in under 1 minute

Nothing here currently, and we don't have any other services readily available as addons. Our current strategy relies on upstream output since there's not a whole lot else go on (no `Kong-Debug` support in TCP to provide the service ID). We'd also need to explicitly close our connection and open a new one to get the new destination.

> When TCPIngress spec changes, the behavior of persistent connections is tested (backend specific)

None currently. This should follow the observed Kong behavior (ignore the changes and keep the connection open and proxied until something else interrupts it) between deck's logic to find and edit existing routes and whatever happens internally in DB-less mode to update existing routes.

>  When TCPIngress spec changes, repeated parallel transient connections to the backend show no failures.

None currently and not sure I understand the test here. If it's just open connection handling, same as the above: once routed, a connection will proxy to its original upstream forever.

> Long running persistent connections (where the backend server doesn't support reconnect mechanisms) disconnect and fail properly when pods change

This should just follow the regular observed FIN-on-close behavior.

> TCPIngress resources can be deleted and the backend route is disconnected in under 1 minute

Handled by https://github.com/Kong/kubernetes-ingress-controller/blob/d4a6ecb8f8e027be79937423b0c0badaf39646e7/test/integration/tcpingress_test.go#L139-L148

>  TCPIngress status is checked for consistent LoadBalancer state between creation and multiple updates to the spec

Nothing across changes, but https://github.com/Kong/kubernetes-ingress-controller/blob/d4a6ecb8f8e027be79937423b0c0badaf39646e7/test/integration/tcpingress_test.go#L101-L116

No TLS tests, which would also require differentiable services, and further a stream listen with `ssl` enabled in the KTF Kong addon.

Didn't look at performance stuff at all.

**Comment by rainest** [comment]
Checked items were either handled by existing tests or will be handled by tests added in https://github.com/Kong/kubernetes-ingress-controller/pull/2041

The remainder have been broken out into their own issues:

https://github.com/Kong/kubernetes-ingress-controller/issues/2067
https://github.com/Kong/kubernetes-ingress-controller/issues/2068
https://github.com/Kong/kubernetes-ingress-controller/issues/2069
