### ISSUE TITLE
Ensure that flag defaults are appropriately set

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1199]
Prioritize defaults compatibility with KIC 1.x.

**Comment by rainest** [comment]
From an initial runthrough, almost everything looks either identical or intentionally changed in a benign way (e.g. the `election-id` default is different, but this doesn't matter).

Only standout was the new `managed-by-railgun` default for `kong-filter-tag`, which we will want to set to the current `managed-by-ingress-controller` eventually to avoid destroying and re-creating all config following an upgrade. Not sure if there was some reason we wanted to keep that distinct during development and/or pre-release.

**Comment by mflendrich** [comment]
Acceptance criteria:
- [ ] Go through all the flags present in KIC 2.x and, for those that have a breaking change, either get them documented in the changelog or create an issue to have that fixed (in the beta blockers milestone)

**Comment by rainest** [comment]
https://gist.github.com/rainest/97e3666d1ee8bee211d3deff198e9612 covers the list as of https://github.com/Kong/kubernetes-ingress-controller/tree/edf338b3efc35ed07ef8f2a338e2f07e837a4548

@shaneutt the flags to disable/enable the various versions of Ingress look like they _did_ change, with the 2.x defaults disabling the older v1beta1 versions. Was that intentional?

The new flags for CRD controllers also didn't exist before, and disable some things we'd normally want (the only thing I'd expect we keep off for now is UDPIngress, since it didn't exist before). However, it doesn't look like simply toggling those on does everything we need (I attempted to see if the KongPlugin flag cleared https://github.com/Kong/kubernetes-ingress-controller/issues/1355, but it did not).

There are two minor changes from constants to literal values in the flag declaration. The actual values are unchanged. I don't see a reason to restore the constants, as they were never used outside the flag parser and are a bit easier to read when the value's just right there in context.
