### ISSUE TITLE
KIC 2.0: Set the metrics and healthz port to the same as in 1.x

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1223]
~The health and metrics servers need to run on the same port, and use the same path routing as in 1.x.~

The health endpoint must remain unchanged w.r.t. KIC 1.x because changing it will cause a crash loop for users of the existing KIC deployment.

We expect little usage of the existing metrics endpoint due to its limited coverage. KIC 2.0 will likely add much more useful metrics due to #1278.

Acceptance criteria:
- [ ] keep the existing healthz endpoint intact
- [ ] expose metrics, possibly on a different endpoint/port, and define an appropriate ServiceMonitor and canonical prometheus service discovery annotations
- [ ] create integration tests that check health and metrics, the tests should run (and succeed) on both 1.x and 2.x without changes.

**Comment by shaneutt** [comment]
Setting as blocked while discussing with the team, because making this work as it did in 1.x with controller runtime is non-trivial.

**Comment by rainest** [comment]
Code-wise, it looks like changing the listen port should be all we need for healthz parity. CR already defaults to exposing a `/healthz` path: https://github.com/kubernetes-sigs/controller-runtime/blob/v0.8.3/pkg/manager/manager.go#L183-L187

There are a few references in files under `railgun/config`. Are these generated from anything, or should I update them manually?

CR provides separate `/healthz` and `/readyz` endpoints on that endpoint, and we should make use of the latter for readiness checks. Old-style config, which used `/healthz` for both, will still work, though it won't technically be correct.

Integration tests may be a bit tricky, since these endpoints aren't normally exposed AFAIK (Kubernetes built-ins check them and they have no Service). Do we have anything else that interacts with Pod IPs in integration tests currently?

**Comment by shaneutt** [comment]
> Do we have anything else that interacts with Pod IPs in integration tests currently?

Not directly to the pods, but if you expose them via Ingress that you could test them that way?

**Comment by rainest** [comment]
https://book.kubebuilder.io/component-config-tutorial/define-config.html suggests that you do just update content under `config/` manually, so that's what I did: https://github.com/Kong/kubernetes-ingress-controller/pull/1283

It looks like Kubebuilder handles ServiceMonitor generation for us (behind a local RBAC proxy):
https://book.kubebuilder.io/reference/metrics.html
https://github.com/Kong/kubernetes-ingress-controller/blob/main/railgun/config/prometheus/monitor.yaml
https://github.com/Kong/kubernetes-ingress-controller/blob/main/railgun/config/default/manager_auth_proxy_patch.yaml

So nothing new there.

The basic (no RBAC proxy) health and metrics listens normally only listen on localhost, which we'd need to override if we wanted to expose them through a Service+Ingress. However, integration tests pose a further challenge: by design, our tests don't run the controller in a Pod at all, and we don't intentionally expose it in any way--it just [runs in the background](https://github.com/Kong/kubernetes-ingress-controller/blob/dc05cce3cfcc553758679ba49619d69890366a16/railgun/test/integration/suite_test.go#L197-L220).

Since it is running directly on the test host, however, it listens there, and f155e28 does work to access it :shrug: The condition for proceeding with the test technically shouldn't be the proxy readiness, but we don't start the background controller until after it. That can probably use a separate event that fires after the controller starts, but I could use some help to understand how that should work.

**Comment by shaneutt** [comment]
> Since it is running directly on the test host, however, it listens there, and [f155e28](https://github.com/Kong/kubernetes-ingress-controller/commit/f155e2831ef4c801339da62f5138fc7abd53b7f6) does work to access it shrug The condition for proceeding with the test technically shouldn't be the proxy readiness, but we don't start the background controller until after it. That can probably use a separate event that fires after the controller starts, but I could use some help to understand how that should work.

How about we sync on this today?
