### ISSUE TITLE
Kong Ingress Controller skipping sync for 'service': timestamp too old

### ISSUE THREAD

**Issue by ravibagri5** [Kong/kubernetes-ingress-controller#1327]
We were running 2 kong (Public and Private) deployed via helm2. Both have different ingress classes and we've recently upgraded the kong 1.3.0(KIC 0.7.0) to the latest version 2.4.0(KIC 1.2). We have migrated the helm2 to helm3 in the upgrade process and faced some issues related to helm migration but the kong upgrade ran fine. The public kong is working fine as expected after the upgrade as we're creating all the routes, services, plugins, etc via terraform. i.e they aren't getting created via kong ingress controller. 

But the private kong's services, routes are getting created by using the ingress class annotation and  KongIngress annotation on Kubernetes ingress object. .i.e
```
   konghq.com/override: kong-ingress-config
    kubernetes.io/ingress.class: kong-pvt
```

The problem is that we're not getting any target IP in the upstream section. Hence, the APIs stopped working. If we add the Kubernetes endpoint IP in the target section manually, the APIs start working so the routing rules and KonggIngress annotation seems to be working fine.  We're getting the below logs in the ingress controller debug mode:
`time="2021-05-17T08:36:29Z" level=debug msg="skipping sync for 'tools/sh.helm.release.v1.tools-kong-pvt.v6': timestamp too old (1621240586499581401 > 1621240584283361408)" component=sync-queue
`
Also we were getting below logs without the debug mode:
`time="2021-05-17T08:06:42Z" level=warning msg="skipping service - getServiceEndpoints failed: no suitable port found" component=store service_name=generation-service.8080
`
Everything is working in the old kong version. @hbagdi Can you please help us here?

**Comment by ravibagri5** [comment]
@shaneutt  Thanks for adding the labels but we're blocked with the upgrade because of this and rolling back to the previous version seems to be the only solution now. It seems to be working fine with a fresh database.

**Comment by shaneutt** [comment]
Hi @ravibagri5 sorry to hear your having trouble, please:

- provide the `KongIngress` and other `Ingress` YAML configurations that are being affected by broken service after the `v1.2.x` upgrade
- provide the (extended) pod logs of the proxy container
- provide the pod logs of the KIC controller manager (this will be the `controller` container in the Kong pod)

**Make sure that you scrub all the above of any sensitive information prior to posting.**

Let me know if you need any help retrieving these.

**Comment by ravibagri5** [comment]
Hi @shaneutt ,
Thank you for responding back. Please find attached the requested log and configuration files. Please let me know in case any other details or information is required here. 

[kic_logs.txt](https://github.com/Kong/kubernetes-ingress-controller/files/6521397/kic_logs.txt)
[proxy_logs.txt](https://github.com/Kong/kubernetes-ingress-controller/files/6521398/proxy_logs.txt)
[kong-ki.yaml.txt](https://github.com/Kong/kubernetes-ingress-controller/files/6521399/kong-ki.yaml.txt)
[ms-ingress.yaml.txt](https://github.com/Kong/kubernetes-ingress-controller/files/6521400/ms-ingress.yaml.txt)

**Comment by shaneutt** [comment]
Thanks @ravibagri5 I've taken a look at these logs and configs, could you please provide copies of the `Services` that are affected by the `no suitable port` issue in the logs?

`generation-service` was the first example you provided, but you can pull a list with this command:

```
$ cat kic_logs.txt | awk '{/no suitable/print$13}' | awk -F '=' '{print$2}' | sort | uniq
```

If you could additionally pick a few of the prominent services that you've seen affected by the upgrade and provide the YAML for those as well I would like to reference them against your version https://github.com/Kong/kubernetes-ingress-controller/blob/22a38e832bb88e2f834fd52e6c279d94ee84b613/pkg/parser/parser.go#L160 and walk that logic with them please.

**Comment by ravibagri5** [comment]
@shaneutt  Sure. I'll replace or remove the log files. We have more than 60 services in 1 namespace and all of them have the same issue after the upgrade. However, those micro-services are accessible from the public kong, and also the APIs of those micro-services are working inside the container using kubeDNS.
PFA the service YAML we're using. Please let me know if you need any other details here. 
[service.yaml.txt](https://github.com/Kong/kubernetes-ingress-controller/files/6522980/service.yaml.txt)

**Comment by shaneutt** [comment]
@ravibagri5 after inspection of the provided **Service** it would appear that the problem is due to misconfiguration of **Ingress** resources:

It seems the **Ingress** resource you provided is pointing at _port 8080_ but the service provided is listening kn _port 80_. 8080 is the port of the pod containers apparently, but thats specific to the **Service** and the **Ingress** resource should not point to that.

Please try reconfiguring your affected **Ingress** resources to point at the relevant **Service's** "port" rather than "targetPort" and then let us know if this resolves your issue.

**Comment by ravibagri5** [comment]
Thanks, @shaneutt. Changing the port solved this issue.  I also noticed this but this ingress was working with the old ingress controller. So can you please let me know why it was working with old KIC with the same port and not working now?
I have gone through all changelog and haven't found anything specific to the ingress record. If there is any change, can you please provide me the link?

**Comment by shaneutt** [comment]
> Thanks, @shaneutt. Changing the port solved this issue. I also noticed this but this ingress was working with the old ingress controller. So can you please let me know why it was working with old KIC with the same port and not working now?
> I have gone through all changelog and haven't found anything specific to the ingress record. If there is any change, can you please provide me the link?

If the `Ingress` resources were using the same configuration on an older version of the KIC with no modification since the update, it would have been expected that they would have failed on that older version as well. I can theorize that something else may have happened during your upgrade process which changed this or there is some unknown bug(s) in the mix. I would recommend building a reproduction environment with the old controller and the new controller to synthesize this upgrade and try and reproduce this in a test tube in order to rule out other environmental issues from the previous cluster.

[Kind](https://github.com/kubernetes-sigs/kind) and [Minikube](https://github.com/kubernetes-sigs/minikube) are tools which can help to build such an environment.

**Comment by ravibagri5** [comment]
We have 14 environments and all of them were created using IaC(Terraform & Ansible). All of the environments have the same KIC version with the same Ingress resource configuration and it's working fine with the old KIC. 
![Screenshot-20210526113553-1095x566](https://user-images.githubusercontent.com/21356335/119610341-21be4480-be0a-11eb-88eb-437a73029124.png)

**Comment by shaneutt** [comment]
> We have 14 environments and all of them were created using IaC(Terraform & Ansible). All of the environments have the same KIC version with the same Ingress resource configuration and it's working fine with the old KIC.

Well that sure is interesting :thinking:

This would have been undocumented (and incorrect) behavior of the pre `v1.x` releases and canonically should never have worked this way (and seemingly was fixed for `v1`). I've conferred with my team and recommend making the configuration adjustments for all of your environments as a manual step in your upgrade process. In a testing environment verify that patching the YAML prior to the upgrade works properly and then communicate a maintenance window the the users of your environments to get the upgrade completed for them.

Let me know your thoughts on all that, and what your expectations are or what you're looking for if this does not otherwise resolve the issue for you?
