### ISSUE TITLE
KIC patch version can fluctuate if rescheduled

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1513]
In the following scenario:
1. the user deploys KIC using any of our methods (both helm and kustomize are affected), the deployment in the cluster pulls some KIC `X.Y` tag (major.minor, implicitly pointing to the latest patch release).  **:warning: Let's assume that the deployment has more than 1 replica :warning:.**
2. user's k8s nodes pull the `X.Y` tag which points to `X.Y.Z` (the latest patch release for the time being)
3. a few days later, we release a new patch version `X.Y.Z+1`. The `X.Y` tag gets reattached from `X.Y.Z` to `X.Y.Z+1`.
4. a few days later, one of the replicas gets rescheduled to a node that does not have `X.Y` in the cache so it pulls the new image.

In that case some nodes in the cluster have the `X.Y.Z` image in the cache and other nodes have the `X.Y.Z+1` image. This means that, depending on which of the replicas wins the leader election at a given time, the version of KIC running in the cluster will be non-deterministic.

This wouldn't happen if our `ImagePullPolicy` was `Always` but it is `IfNotPresent` now.

**Comment by rainest** [comment]
Is this not also the case with `Always`? Still-running replicas on `X.Y.Z` will not re-pull the image on their kubelet or restart if some other kubelet pulls `X.Y.Z+1`. `Always` corrects the issue if you run a `rollout restart` but not if some individual replica reschedules and the others remain as-is.

This seems like it's just inherent to the use of major-minor tags for image configuration, so if we want that to be viable the onus is on us to ensure that newer patch releases are at least compatible with one another. The meaning of "compatible" is kind of nebulous though, since controller instances don't really interact with one another. You either have:

- DB-less, where each controller manages its own proxy instance. Changes that affect proxy configuration manifest as differences in each proxy instance's behavior.
- DB-backed, where some arbitrary controller instance manages all proxies' configuration, and the proxy behavior is determined by whichever instance happens to be the leader. This will often be an older version instance, simply because those instances will be longer-lived and will more likely have already held leadership or grabbed it while newer version instances were spawning.

As a result, _any_ change that affects proxy behavior is effectively breaking, even if it's a fix.

**Comment by shaneutt** [comment]
Closing as stale, let's re-open if we feel this requires further attention.
