### ISSUE TITLE
[kic2.0] ingress updates stuck on same SHA

### ISSUE THREAD

**Issue by ccfishk** [Kong/kubernetes-ingress-controller#1538]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

   Continue Deploying ingresses into the cluster, controller stops updating configuration to kong after around 9 ingresses. 

**Kong Ingress controller version**
  controller next branch code

**Kong or Kong Enterprise version**
 proxy 2.4.0

### Kubernetes version

**paste `kubectl version` output**

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened
  Controller stops updating configuration to proxy

### Steps To Reproduce

1. deploy 9 ingress  
2. check ingress status update
3. deploy 10 ingress
3.  the 10th ingress never gets update
4.
for example, all the new ingress after 9 is generated with the same SHA.
sha b3e00b2686bba69c1eb37dfa0bddfdc935e360b5ac7c26783c8a6cc665b6128f
sha edd3e90ed4c8d8e88e9fc24a4e8915aa53f052dc65fc1963c4a0997b800e9594 

sha eaad862ab61d3034e9b61eb419cfbe39ccbbf0172ff4437c0710db3e099152f1 
sha eaad862ab61d3034e9b61eb419cfbe39ccbbf0172ff4437c0710db3e099152f1

**Comment by shaneutt** [comment]
I was unable to reproduce the original problem here by way of tests which I've added in:

https://github.com/Kong/kubernetes-ingress-controller/pull/1556

Now that doesn't mean there isn't a problem, but I can't see the SHA problem as described here.

How would you feel about adding a test case that proves the problem (e.g. it fails) so that we can use that as a basis to make fixes which turn it green :heavy_check_mark: ?

**Comment by ccfishk** [comment]
Fixed in https://github.com/Kong/kubernetes-ingress-controller/pull/1568
