### ISSUE TITLE
Very little documentation for DB version of Kong with Kubernetes

### ISSUE THREAD

**Issue by reetik-raj** [Kong/kubernetes-ingress-controller#1569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

We did a POC by integrating Kong OSS(Postgres DB version) with our company requirements and we were pretty satisfied by what we were able to achieve. Now we have dockerized everything along with our custom plugins and we want to deploy this to production. We use K8s with EKS in our production and are planning to integrate Kong Ingress Controller along with this. I went through your official documentation and found that you recommended using a DB-less version of Kong with Kubernetes deployments. We are hesitant to switch to this due to two reasons - 
1. We don't want to lose Konga which we are using to easily update any services, routes, consumers, plugins, etc from a nice GUI.
2. Switching to the DB-less version will force us to update all our thousands of customers with their authentication details in the YAML file which might make it very hard to maintain and may also cause memory issues (mind you we plan to use in-memory caching too).

Also, I found that there were very few resources and tutorials covering the DB version Kong deployment on Kubernetes as all the tutorials are focused on the DB-less versions. What do you people suggest? Also, if I am missing something or if you have relevant documentation for the DB version Kong K8s deployment please let me know. 

Looking forward to your reply. 
Thank you

**Comment by mflendrich** [comment]
@reetik-raj,

Thanks for your input.
We provide a deployment manifest that deploys KIC together with a PostgreSQL database: https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single/all-in-one-postgres.yaml

Using this file instead of the DB-less all-in-one manifest referenced by our DB-less guides should suffice to make a DB-enabled installation. I agree with your observation that our documentation is centered around DB-less today.

Is the link above helpful in your situation? If not, please let us know what specifically you're trying to do that is missing documentation.

**Comment by namanbajpayi** [comment]
hey @mflendrich , thanks for the reverting. 
Will above deployment also give us konga? i mean admin gui.?
