### ISSUE TITLE
Finalize the shape of kustomize manifests of 2.0

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Decide how to continue after https://github.com/Kong/kubernetes-ingress-controller/issues/1667.
Should we expose the kubebuilder generated manifests (under `config`) to the user (alongside the single manifests), or keep them "private" in a separate path (`config/`) and maintain the "user-facing" manifests (single manifests) under `deploy/` as they were in KIC 1.x?

**Comment by rainest** [comment]
I believe https://github.com/Kong/kubernetes-ingress-controller/pull/1682 completes this. Unsure if we have any remaining things we wanted to address as there aren't acceptance criteria on this yet.

**Comment by shaneutt** [comment]
> I believe #1682 completes this. Unsure if we have any remaining things we wanted to address as there aren't acceptance criteria on this yet.

++, it appears with #1682 we have completed this.

**Comment by rainest** [comment]
I suppose for the actual GA release we will move the stuff currently in `deploy/single-v2` into `deploy/single`. There are also some differences in naming between the two:

```
10:59:05-0700 yagody $ ls deploy/single
all-in-one-dbless-k4k8s-enterprise.yaml  all-in-one-dbless.yaml  all-in-one-postgres-enterprise.yaml  all-in-one-postgres.yaml
11:01:45-0700 yagody $ ls deploy/single-v2 
all-in-one-dbless.yaml	all-in-one-enterprise-dbless.yaml  all-in-one-enterprise-postgres.yaml	all-in-one-postgres.yaml
```
I'd like to get away from the `all-in-one-dbless-k4k8s-enterprise.yaml` name and just use `all-in-one-dbless-enterprise.yaml`, since it kinda refers to something that no longer exists. We need to figure out whatever bitly link goes to that and make a new one.

**Comment by mflendrich** [comment]
> I believe #1682 completes this.
