### ISSUE TITLE
Enforce deterministic KongConsumer credentials configurations when constraints are violated

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1722]
We currently drop credentials when they are found to be in violation of unique constraints, however we don't do this in a deterministic way and so the results can be confusing for the end-user as credentials may occasionally enable/disable against the other credentials they are in conflict with.

The purpose of this issue is to make these credentials deterministic so that other updates wouldn't change the credentials configuration for a consumer.

This is a follow-up to #729

Acceptance Criteria:
- [ ] credentials for `KongConsumers` apply in a determinist way when some credentials are dropped to to constraint violations

**Comment by shaneutt** [comment]
@Kong/team-k8s I propose the following solution to the problem that would meet the acceptance criteria I added above:

- [ ] when there are constraint violations, drop and log errors for ALL credentials rather than just the last ones seen in a list

LMKWYT

**Comment by rainest** [comment]
We should avoid two problem scenarios:

- Two consumers have a credential with the same value for a unique key. The order of [the consumer list](https://github.com/Kong/kubernetes-ingress-controller/blob/757151acb4a1cd86659562176d84522abec10d11/internal/kongstate/kongstate.go#L59) (effectively the order of results returned from the Kubernetes API, since it goes from [the store](https://github.com/Kong/kubernetes-ingress-controller/blob/c4be27d906d569950fcfb23b86f3bd3d1b898ef5/internal/store/store.go#L584) to the [generated clientset](https://github.com/Kong/kubernetes-ingress-controller/blob/757151acb4a1cd86659562176d84522abec10d11/pkg/clientset/typed/configuration/v1/kongconsumer.go#L80-L93)) is random. The first time we generate configuration, consumerA is processed first and associated with the duplicated credential. The next time, consumerB is processed first, and the association flip-flops. The next time the same thing happens, etc.
- consumerA has an existing credential, and a client is actively using this credential for important requests. They also have an ACL association that grants them access to perform these requests. Hapless sysadmin dutifully processes new hire paperwork and adds consumerB with a credential that unfortunately collides with consumerA's credential and an ACL that grants them access to not very much. The order used by `FillConsumersAndCredentials()` is _not_ random, but uses a sort that processes consumerB before consumerA. consumerA spontaneously finds that their credential now identifies them as consumerB, that they have lost all access as such, and that all their requests now result in 403s.

AFAIK a nebulous "initially added to config" sort precedence is the only thing that avoids the second issue. As Michal noted, resource timestamps aren't guaranteed reliable for this.

I think, therefore, that there likely are no good options for sort order if we use this in actual config generation, and moving this to the admission webhook is the only safe option. This is not guaranteed to avoid the error condition because it's an optional component, but I'd argue that's fine--the same is generally true for other admission validations (if you create an invalid plugin configuration without admission, the controller will happily attempt to create it, encounter an error, and cease applying new configuration until you fix the bad plugin) and our recommendation for avoiding that scenario is already to use the admission controller. AFAIK we only don't enable it by default because we can't provision certificates for it (come to think of it, we should enable it by default in the chart, which can).

**Comment by shaneutt** [comment]
After considering those points, and some talk in Slack it seems that the solution we have so far really ultimately isn't going to work.

There are several factors at risk here and I ultimately agree with @rainest that the best option (specifically, the one that is going to stop us from spending an incredibly large amount of time on solving this problem) is going to be to take the new validation code and move it into the admission webhook.

I've noted this in the original issue, and started a revert PR to resolve this issue:

- https://github.com/Kong/kubernetes-ingress-controller/issues/729#issuecomment-901336616
- https://github.com/Kong/kubernetes-ingress-controller/pull/1729
