### ISSUE TITLE
verify the v1 ingress resources in the getting stated guide

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

It seems that example `Ingress` resources like [this one](https://kic-v2-beta--kongdocs.netlify.app/kubernetes-ingress-controller/2.0.x/guides/getting-started/#basic-proxy) are broken in the Getting Started guide, because they use the v1beta1 schema and the v1 apiversion.

### Proposed Solution

Ensure that all items from the guides that have been updated to ingress v1 work.

**Comment by rainest** [comment]
https://github.com/Kong/docs.konghq.com/pull/3157 seeks to correct these.

**Comment by rainest** [comment]
Having not received further review on https://github.com/Kong/docs.konghq.com/pull/3157, merging that closing this based on the spot checks I performed for that since I made the same changes to Ingresses throughout. That makes the corrected Ingresses available in the v2 doc branch for the audit tickets, and the audit tickets for individual docs should find any that were missed.
