### ISSUE TITLE
KongIngress CRD from v2 allinone-dbless template fails to apply in k8s 1.21 (GKE)

### ISSUE THREAD

**Issue by thejosephstevens** [Kong/kubernetes-ingress-controller#1811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I apply the CRDs found [here](https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single-v2/all-in-one-dbless.yaml) to my GKE cluster (version 1.21), I get this failure. Specifically, they're in a file and I'm running `kubectl apply -f FILENAME`

```
error validating data: [ValidationError(CustomResourceDefinition.spec.versions[0]): missing required field "served" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion, ValidationError(CustomResourceDefinition.spec.versions[0]): missing required field "storage" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion]; if you choose to ignore these errors, turn validation off with --validate=false
```

### Expected Behavior

The CRDs should apply successfully

### Steps To Reproduce

```markdown
1. Download the file from [here](https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single-v2/all-in-one-dbless.yaml)
2. Create a GKE 1.21 cluster (version information below)
3. Attempt to apply the file with `kubectl apply -f FILENAME`
```

### Kong Ingress Controller version

```shell
`2.0.0-beta.2`, but we're not getting to the application lifecycle yet, this is just CRD validation issues.
```

### Kubernetes version

```shell
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3-gke.901", GitCommit:"79ef293e0b25a2b58efc0e3437e5eedf5a500e33", GitTreeState:"clean", BuildDate:"2021-08-07T05:08:15Z", GoVersion:"go1.16.1b7", Compiler:"gc", Platform:"linux/amd64"}
```

### Anything else?

Nothing else. I'm going to go ahead and try upgrading my kubectl to make sure that's not the issue, I'll follow up if that fixes it.

**Comment by shaneutt** [comment]
Verified this is an issue on `kind` as well, so it's easy to reproduce. Thanks for reporting this @thejosephstevens I'll get to work on it.

Also worth noting that this issue is directly related to https://github.com/Kong/kubernetes-ingress-controller/issues/756: our CI missed this because it tests the base configurations, but not the compiled one and something is apparently breaking down in that compilation step. It will be my goal to add the compiled manifests to our test suite to avoid regressions like this in the future.

**Comment by shaneutt** [comment]
Verified this is an issue on `kind` as well, so it's easy to reproduce. Thanks for reporting this @thejosephstevens I'll get to work on it.

Also worth noting that this issue is directly related to https://github.com/Kong/kubernetes-ingress-controller/issues/756: our CI missed this because it tests the base configurations, but not the compiled one and something is apparently breaking down in that compilation step. I'll fix this but then it will also be my goal to add the compiled manifests to our test suite to avoid regressions like this in the future.

**Comment by shaneutt** [comment]
Turns out a little over a week ago we added this regression by adding a `kustomize` patch which was inadvertently deleting the required fields. Because integration tests at the time of writing use the CRD manifests directly and the maintainers predominantly test with the [Helm chart](https://github.com/kong/charts) this got missed for several days.

https://github.com/Kong/kubernetes-ingress-controller/pull/1813 fixes the problem introduced by the `kustomize` patch, but also adds new tests that do basic deploy tests of the "all-in-one" style manifests to help us avoid regressions like this in the future.
