### ISSUE TITLE
Include both --watch-namespaces and --watch-namespace

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1843]
For convenience and to improve user experience the purpose of this task is to add both `--watch-namespaces` and `--watch-namespace` aliases in KIC controller manager. This is a minor thing, but for almost no cost its expected to improve user experience ever so slightly from a linguistic standpoint.

Acceptance Criteria:
- [ ] `--watch-namespace` and `--watch-namespaces` are aliases to the same functionality
- [ ] the documentation points out that you can optionally add the `s`

**Comment by mflendrich** [comment]
-1 from me:

I'm afraid that implementing this alias creates a new class of problems: duplicate env variables, and precedence/shadowing thereof.

What happens if the user creates CONTROLLER_WATCH_NAMESPACES, and then tries to override it by setting CONTROLLER_WATCH_NAMESPACE elsewhere?

Will the behavior be different if we swap the env variables in question?

I feel that the tradeoff between the added value and the problems created isn't in the positive.

**Comment by shaneutt** [comment]
It's a fair point. I invite @Kong/team-k8s to chime in but if nobody else makes a case _for_ doing this other than myself I'm OK with considering it declined.

**Comment by mflendrich** [comment]
The team decided "won't fix"
