### ISSUE TITLE
Kong ingress controller should be able to manage ingress itself and just accept kongIngress definitions 

### ISSUE THREAD

**Issue by vivekgkwd** [Kong/kubernetes-ingress-controller#1852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

we currently end up creating 1 ingress object per route rather than manually grouping the routes with same properties in one ingress(only for convenience)

### Proposed Solution

Accept all inputs required for creating an ingress in kongingress definition and create/manage kubernetes ingress objects with ingress controller

**Comment by esatterwhite** [comment]
discovery of services via annotations would also reduce the need for multiple ingress definitions
#1891

**Comment by shaneutt** [comment]
Can you please help me to better understand the impact and user stories that would help inform a solution to this problem for you?

**Comment by esatterwhite** [comment]
I think this should be re-opened and actively perused. If you were to have, say 10 services that compose 2 separate domains under a single ingress - Web applications, Websocket applications, basic CRUD-y API applications and some services the move high volume data. Configuring each set of service in kong via the ingress controller can be rather difficult and result in a log of additional resources to pull off.

we have had to create separate `Ingress` resources to group applications that serve generally the same functions so we can apply different `KongIngress` resources to them. In some cases we have to have multiple `KongIngress` resources depending on what we might need to configure, because some things may need to apply to the `Ingress` and some things may need to apply to the `Service`.

To really get a granular level of control you almost need to have 1:1:1 of `Service`:`Ingress`:`KongIngress` so you don't have to have multiple independent deployments of the controller + proxy

**Comment by shaneutt** [comment]
Thanks for the update and additional context. Based on your report I would characterize the current problem you would like to see solved (in that you have to create multiple `Ingress` resources to apply different `KongIngress` resources to them) as being one of efficiency. I'm also curious about the actual underlying configuration options that are involved when you have to create multiple `Ingress` resources: could you please provide an ideally working example of some configurations where you have to create separate `Ingress` resources for separate `KongIngress` rules to help illustrate the problem? We are considering trying to provide alternative ways to express configurations currently expressed with `KongIngress` using [Gateway API](https://github.com/kubernetes-sigs/gateway-api) support and other means so to better understand the details of the problem might provide us helpful insights to suggest other solutions as well :thinking:
