### ISSUE TITLE
Kong seems to lose its configuration after some minutes

### ISSUE THREAD

**Issue by stestet** [Kong/kubernetes-ingress-controller#200]
I set up minishift on a Windows and on a Mac according to [this](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/deployment/openshift.md).
Then I did [this](https://docs.konghq.com/0.14.x/getting-started/configuring-a-service/).

Then I polled the Kong Services (http GET http://kong-url/services). In the beginning the service appears as configured. After some minutes the service disappears.

I have this issue on Windows and on Mac... Ony idea why?
Thanks and best regards
Stefan

**Comment by mativillagra** [comment]
Hello @stestet . 

Yes I think that is an expected behavior when using Kong as an ingress-controller , to be able to creates routes / services / plugins persistent you need to used 

[](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/custom-resources.md#custom-resource-definitions)

@hbagdi wrote an example on exposing an external application I paste the url here. 

[](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/external-service/externalname.md)

Hope it helps.

**Comment by stestet** [comment]
Thank you, @mativillagra. It would have been appropriate of me to read the whole documentation... Greetings to argentina.
