### ISSUE TITLE
Controller Testing using kubebuilder envtest

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#2006]
### Problem Statement

Historically leading up to KIC `v2.0.0` release we put a stronger emphasis on integration tests than unit tests and we focused more of our efforts on institutionalizing integration testing (via tools like [KTF](https://github.com/kong/kubernetes-testing-framework)) throughout the codebase. This served us well, but leaves something to be desired for smaller and more quickly testable controllers with a faster feedback loop. There are several options available from `controller-runtime` and some other places to test controllers in a way that more resembles unit tests (with quick feedback) and the purpose of this issue is to pick a method, document it, and start adding the framework into our existing controller code.

### Proposed Solution

- [ ] integrate `envtest` from `controller-runtime` (see https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html)

### Acceptance Criteria

- [ ] as a contributor I have provisions and examples available to me to quickly write tests for my controllers for fast feedback and strong code coverage.
- [ ] all controllers that existed prior to this work are retrofitted with controller tests

**Comment by rainest** [comment]
Do we know of something that envtest would provide us over KTF (beyond just using a common framework)? The [feature set](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest) doesn't appear that rich.

While my PoC run wasn't entirely successful, it at least got me familiar with how these tests are written. It doesn't seem like we'd gain much over the KTF integration test approach, since:
* It doesn't look like these are unit tests, as the Kubernetes components actually run and are not mocked, they're just maybe a bit more lightweight than KIND.
* Once you get past the boilerplate to set up the testing environment (essentially a one-off, though the example has you starting a minimal manager with _only_ the tested controller set up), the tests are [essentially the same as what we do for integration tests currently](https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html#testing-your-controllers-behavior): you create resources and observe the resulting changes in the environment.

Testing the controllers alone also poses a challenge because most of our controllers (Gateway excepted) don't do much of anything on their own: they listen for events and then call either `Proxy.DeleteObject()` or `Proxy.UpdateObject()` to let the sync loop then build an up-to-date Kong state based on the contents of the proxy cache. Without a Kong instance (for the alternate "not hooked up to Kong" interpretation of "unit test") about all we can do is check the proxy cache contents after.

---

**Other notes**

Not having started with a Kubebuilder project from the start appears to hamstring us a bit, since the tools for adding API/controller boilerplate don't work without a main.go in our root (it's instead under `internal/cmd`). The large set of generated controllers doesn't really mesh with the expected project layout either.

The ginkgo and zap usage in the test example and boilerplate are at odds with our existing test framework (granted we already have multiple) and logger choices. Will be a bit annoying to rip out.

Threw together a KongPlugin PoC without ripping out the unwanted libraries. The diff in [kongplugin_test.txt](https://github.com/Kong/kubernetes-ingress-controller/files/7974835/kongplugin_test.txt) runs (it does require [setting up envtest](https://book.kubebuilder.io/reference/envtest.html), though unsuccessfully. Unsure what I've screwed up here (it does look like the CRD was installed, but I don't know how to interrogate envtest environments to try and confirm):

```
Failure [4.434 seconds]
[BeforeSuite] BeforeSuite 
/home/traines/src/ingress-controller/internal/controllers/configuration/suite_test.go:56

  Unexpected error:
      <*runtime.notRegisteredErr | 0xc000201560>: {
          schemeName: "pkg/runtime/scheme.go:100",
          gvk: {Group: "", Version: "", Kind: ""},
          target: nil,
          t: <*reflect.rtype | 0x1704220>{size: 0x188, ptrdata: 0x178, hash: 2817621761, tflag: 7, align: 8, fieldAlign: 8, kind: 25, equal: nil, gcdata: 85, str: 93488, ptrToThis: 3023008},
      }
      no kind is registered for the type v1.KongPlugin in scheme "pkg/runtime/scheme.go:100"
  occurred

  /home/traines/src/ingress-controller/internal/controllers/configuration/suite_test.go:88
------------------------------
```

**Comment by shaneutt** [comment]
> Do we know of something that envtest would provide us over KTF (beyond just using a common framework)? The feature set doesn't appear that rich.

Ostensibly it should make it possible to run tests for controllers more at the speed of unit tests and without having to run anything except Golang binaries.

Years ago I remember talking with colleagues about running the components which are now in envtest as libraries. If I recall correctly the problem with this was the dependency management but I wonder if it's better these days :thinking: 

>Testing the controllers alone also poses a challenge because most of our controllers (Gateway excepted) don't do much of anything on their own: they listen for events and then call either Proxy.DeleteObject() or Proxy.UpdateObject() to let the sync loop then build an up-to-date Kong state based on the contents of the proxy cache. Without a Kong instance (for the alternate "not hooked up to Kong" interpretation of "unit test") about all we can do is check the proxy cache contents after.

I think in the shorter term, envtests would be more suited for Gateway APIs tests than or previously existing controllers, which is what you seem to be suggesting here and so I agree.

> Not having started with a Kubebuilder project from the start appears to hamstring us a bit, since the tools for adding API/controller boilerplate don't work without a main.go in our root (it's instead under internal/cmd). The large set of generated controllers doesn't really mesh with the expected project layout either.

afaik from previously trying to improve this upstream: if we were to move the main.go, the pkg/apis and the internal/controllers into their expected locations things should start to work just fine. Ultimately the fact that kubebuilder doesn't support these alternative locations is in my opinionate a big miss, so I think it's also entirely reasonable for us to take the approach of adding the improvements to support this in upstream Kubebuilder ourselves.

> The ginkgo and zap usage in the test example and boilerplate are at odds with our existing test framework (granted we already have multiple) and logger choices. Will be a bit annoying to rip out.

We could discuss this a bit further. Most of upstream is happy with ginkgo but we have historically been built on testify. I don't know what our appetite is for having multiple testing patterns but I'm assuming it's pretty low (lol) so yeah I mean teasing through these and changing them is probably the way to go.

**Comment by mflendrich** [comment]
"won't fix" - we can unit-test controllers without the kubebuilder test env if necessary, and we have KTF that achieves similar functionality that's sufficient for us.
