### ISSUE TITLE
`service-upstream` support for HTTPRoute

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Ensure that `HTTPRoute` supports the `service-upstream` annotation

### Proposed Solution

Make the parser honor the `service-upstream` on attached `Service`s.

### Additional information

Might be already supported - needs verification

### Acceptance Criteria

- [x] HTTPRoutes referencing a service with `service-upstream: true` works by pointing at the service IP and not at the service's endpoints

**Comment by rainest** [comment]
Manual test to confirm this works out of the box because it's handled entirely within the Service parser code, and agnostic of what resource references that Service: https://gist.github.com/rainest/1b77021c41f56003ac9eb85456df46dd

For reference, in tests, the only inputs are the Service:
https://github.com/Kong/kubernetes-ingress-controller/blob/cc8ebfcf584d2aa163532d6bab1971ae08539ac9/internal/parser/parser_test.go#L3718-L3751
https://github.com/Kong/kubernetes-ingress-controller/blob/cc8ebfcf584d2aa163532d6bab1971ae08539ac9/internal/parser/parser_test.go#L4004-L4011

The tested functions is called from within `getUpstreams()`, which builds it by looping over the service Name->Service map:
https://github.com/Kong/kubernetes-ingress-controller/blob/cc8ebfcf584d2aa163532d6bab1971ae08539ac9/internal/parser/parser_test.go#L4004-L4011
https://github.com/Kong/kubernetes-ingress-controller/blob/cc8ebfcf584d2aa163532d6bab1971ae08539ac9/internal/parser/parser.go#L78-L83

**Comment by shaneutt** [comment]
Thanks for checking :vulcan_salute:
