### ISSUE TITLE
Tag every resource in Kong that is managed by the ingress controller

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#246]
Kong Ingress Controller can tag every resource that it manages in Kong's database.
This allows for cases where some resources in Kong are not managed by Kong Ingress controller, allowing users to configure some consumers and credentials via CRDs in k8s while others are instantiated via Admin API dynamically. 

This also ties directly with Kong Service Mesh integration where the entire service mesh could be configured using another controller or via another mechanism outside of the Ingress Controller. In such a case, Ingress Controller should manage only entities that it has created and should not concern with entities in Kong's DB created by other means.

**Comment by AnneXXB** [comment]
I saw the warning users should not to add kong resource by admin API  in the readme,but  could you please add some reasons. I am a little incomprehensible, is there any plan to fix it ?

**Comment by julianguinard** [comment]
@AnneXXB This is because kong-ingress-controller will periodically resync Kong entities (users, routes, plugins...) using its own [Kubernetes Custom Resource Definitions](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/custom-resources.md), hence deleting everything that was declared using Kong's Admin API

Currently, the only possible workaround is to create these Kubernetes Custom Resource Definitions using the Kubernetes API instead of Kong's API, as I have been told by @hbagdi in [issue 105](https://github.com/Kong/kubernetes-ingress-controller/issues/105#issuecomment-478940777)

**Comment by AnneXXB** [comment]
@julianguinard  Thank you for your answer。
1、Our team are busy with integrating kong and istio.  Do you any clear plan to fix this problem? if so, when or which version? 
2、Why there is no vendor package in the source code package? Could you please upload the vendor package.There are so mang dependency packages we cannot get because of  the national-firewall. thank you .

**Comment by hbagdi** [comment]
@AnneXXB 

> 1、Our team are busy with integrating kong and istio. Do you any clear plan to fix this problem? if so, when or which version?

This is high on the roadmap and will be fixed with the version coming after 0.4.0.
I'd like to know more why this particular feature is a blocker for integration with Istio in your use case. Are you planning to manually configure Kong or with another integration within Istio?

> 2、Why there is no vendor package in the source code package? Could you please upload the vendor package.There are so mang dependency packages we cannot get because of the national-firewall. thank you .

Please use dep to manage the dependencies of this project. You can use a proxy to put it inside a fork. We removed the `vendor` package a while ago and have not plans on adding it back. We feel that Go's dependency management is mature enough now to not vendor the dependencies inside a VCS.
