### ISSUE TITLE
created_at of created_at will change when ingress controller sync rules

### ISSUE THREAD

**Issue by gung-rgb** [Kong/kubernetes-ingress-controller#2472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For Example:
```json
{
  "id": "e6555d2f-bcbc-5741-a501-2ce0ca4e3801",
  "tags": null,
  "updated_at": 1651917533,
  "destinations": null,
  "headers": null,
  "protocols": [
    "http",
    "https"
  ],
  "strip_path": true,
  "created_at": 111111111,
  "snis": null,
  "name": "hello",
  "hosts": [
    "hellotest.com"
  ],
  "methods": null,
  "preserve_host": false,
  "regex_priority": 100,
  "paths": [
    "/"
  ],
  "sources": null,
  "response_buffering": true,
  "https_redirect_status_code": 426,
  "path_handling": "v0",
  "request_buffering": true
}
```

when ingress sync with http put, created at change to now() by kong admin api:

```
{
  "id": "e6555d2f-bcbc-5741-a501-2ce0ca4e3801",
  "tags": null,
  "updated_at": 1651917533,
  "destinations": null,
  "headers": null,
  "protocols": [
    "http",
    "https"
  ],
  "strip_path": true,
  "created_at": 1651918758,
  "snis": null,
  "name": "hello",
  "hosts": [
    "hellotest.com"
  ],
  "methods": null,
  "preserve_host": false,
  "regex_priority": 100,
  "paths": [
    "/"
  ],
  "sources": null,
  "response_buffering": true,
  "https_redirect_status_code": 426,
  "path_handling": "v0",
  "request_buffering": true
}
```

### Expected Behavior

created_at should not change since the entity created.

### Kong Ingress Controller version

```shell
v1.3.1
```

**Comment by shaneutt** [comment]
Thanks for the report, I have a couple follow up questions:

- are you using DBLESS mode or DB mode with postgres?
- I see you're using `v1.3.1` of the ingress controller, what version of the Kong Gateway are you using?

**Comment by gung-rgb** [comment]
> 

1. I use DB mode with pg
2. my kong version is 2.2

**Comment by shaneutt** [comment]
Thank you. Part of how the ingress controller works is that it is the "source of truth" for Gateway configuration when in use, and it actively re-applies that "truth" on a regular basis when there are changes. A couple of follow up questions that will help me:

1. are there changes happening at a regular consistency to resources like `Ingress`, `Secrets`, or even `KongIngress`, `KongPlugins` e.t.c.?
2. ultimately, what problem does this update to the `created_at` cause you?

**Comment by rainest** [comment]
This appears to be inherent to how Kong handles PUTs if you do not provide timestamps (which is how deck, and therefore the controller, handles updates): https://gist.github.com/rainest/a01d7f5b78f72982beffe8e3a598ad3a

You'll encounter a cache miss regardless: we only perform an update if some other aspect of the route changed, so proxy instances will need to reload it from the database to pull in that change.

You should not rely on the `A.created_at < B.created_at` sort rule of last resort for route ordering. If the routes do not use prefixes, they will sort based the prior condition that selects the more specific route. If they have overlapping regular expressions, you should [set their priority](https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/references/annotations/#konghqcomregex-priority) to determine the order. Is there some reason those would not work in your case?

The `created_at` sort is essentially only in place because we want route selection to be deterministic (if the route set has not changed, sending the same request repeatedly should always result in the same route match), and we need _some_ fallback condition to check in case all other sorting rules resulted in a tie to guarantee that. We probably should have a further fallback alphabet sort of the IDs in case the timestamps are the same--in practice, this apparently hasn't been a source of issues, but I'm still going to recommend it to the gateway team.

**Comment by gung-rgb** [comment]
> Is there some reason those would not work in your case

No, But is strange to change created_at.

**Comment by rainest** [comment]
I don't recall exactly, but I believe there's a reason we use PUT instead of PATCH for updates in that library, and that changing the created_at time was considered a benign side effect that we didn't need to correct. Going ahead and closing this since the non-fallback sort priorities will work here.
