### ISSUE TITLE
ARM64 Image Builds

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#2500]
We have the machinery to build ARM64 images: https://github.com/Kong/kubernetes-ingress-controller/pull/2387

We need to make such an image available for deployment.

Acceptance Criteria:
- [ ] we document our ARM64 build?
- [x] releases now push a new multi-arch build including an ARM64 image
  - this happens in [release.yaml](https://github.com/Kong/kubernetes-ingress-controller/blob/cd39352e7696c0064c265723246a5f477377e115/.github/workflows/release.yaml#L110-L153) merged as part of #2387
- [ ] I can `docker pull` KIC images natively on an ARM64 system
  - [x] nightly images in https://hub.docker.com/r/kong/nightly-ingress-controller/tags
  - [ ] release images

**Comment by pmalek** [comment]
With #2542 merged, I now propose to enlist all the os+arch combinations in the [Container images section](https://github.com/Kong/kubernetes-ingress-controller#container-images) including arm64 but adding an asterisk that the first images with arm64 support will be uploaded as part of next release.

WDYT?

**Comment by shaneutt** [comment]
> With #2542 merged, I now propose to enlist all the os+arch combinations in the [Container images section](https://github.com/Kong/kubernetes-ingress-controller#container-images) including arm64 but adding an asterisk that the first images with arm64 support will be uploaded as part of next release.
> 
> WDYT?

SGTM :+1:

**Comment by pmalek** [comment]
Adding mention of supported platforms: #2546

**Comment by pmalek** [comment]
BTW I believe this should be placed in [Release 2.4.0](https://github.com/Kong/kubernetes-ingress-controller/milestone/26) rather than [Release v2.5.0](https://github.com/Kong/kubernetes-ingress-controller/milestone/24) because we'll end up having an arm64 container image anyway due to the [release action already having arm64 builds enabled](https://github.com/Kong/kubernetes-ingress-controller/blob/629a6a03de1e79f25899a15f1bc278d3263d2459/.github/workflows/release.yaml#L110-L153).

WDYT @Kong/team-k8s ?

**Comment by shaneutt** [comment]
Yes, feel free to put it in release `v2.4.0` if it's going to be complete at that point :+1:

**Comment by pmalek** [comment]
So at this point we have nightlies, we **will** have release image as soon as 2.4 rolls out.

As soon as #2546 gets merged we'll have it documented (that we provide arm64 images) and the release and nightly pipelines already push arm64 images.

Hence I'm assigning this into [Release 2.4.0](https://github.com/Kong/kubernetes-ingress-controller/milestone/26) and I'm closing it since there is not more actions to be done here apart from releasing 2.4.
