### ISSUE TITLE
Kong ingress controller is applying ingress rules from other namespaces

### ISSUE THREAD

**Issue by eamonnmcevoy** [Kong/kubernetes-ingress-controller#254]
### Summary

Kong ingress controller is applying ingress rules from other namespaces. In my cluster I have 2 namespaces, each with a kong ingress controller. When I check the `/routes` endpoint, I see a route for all ingress rules in the cluster, regardless of namespace

**Version**
helm chart 0.9.8

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.11", GitCommit:"1bfeeb6f212135a22dc787b73e1980e5bccef13d", GitTreeState:"clean", BuildDate:"2018-09-28T21:35:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

running on AKS

### Expected behaviour
Kong ingress controller should only generate routes for ingress rules in the same namespace

### Steps To Reproduce

1. Deploy 2 ingress controllers in separate namespaces
2. Deploy an ingress rule to namespace A
3. Deploy an ingress rule to namespace B
4. Call `/routes` on namespace A ingress controller.
5. 2 Routes will be returned, one for each ingress

**Comment by hbagdi** [comment]
> Kong ingress controller should only generate routes for ingress rules in the same namespace

This is not the expected behavior.
Ingress controller will satisfy the Ingress from all namespaces by default.

You've two options:

- Use the `--watch-namespace` CLI flag in the Ingress controller to limit it to a single namespace.
- Use `ingress.class` [annotation](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/annotations.md#kubernetesioingressclass) on your Ingress resources and your Kong CRDS, to filter the Ingress that a particular Ingress Controller should satisfy.
