### ISSUE TITLE
Ingress Controller seems to be creating a new secret everytime a configuration change is detected

### ISSUE THREAD

**Issue by Pixcell** [Kong/kubernetes-ingress-controller#2545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I deployed kong kubernetes ingress controller in one namespace, set up to proxy lot of different http routes towards different services in multiple namespaces using ingress rules.
(I am happy to provide more details on the configuration if needed, but I don't want to overload the ticket to start with).

Everytime a config change happens (I.E: a ingress rule is removed or added), a new service account secret `kong-token-xxxx` is created in my namespace
```
kubectl -n controller-ingress-0 get secrets                                                                                                                                                           

NAME                  TYPE                                  DATA   AGE
default-token-hbczc   kubernetes.io/service-account-token   3      14m
kong-tls              kubernetes.io/tls                     2      14m
kong-token-42h9w      kubernetes.io/service-account-token   3      11m
kong-token-dkhff      kubernetes.io/service-account-token   3      20s
kong-token-ghk7g      kubernetes.io/service-account-token   3      12m
kong-token-gndt4      kubernetes.io/service-account-token   3      13m
kong-token-mtddd      kubernetes.io/service-account-token   3      4m16s
kong-token-t2zql      kubernetes.io/service-account-token   3      10m
kong-token-vj2f7      kubernetes.io/service-account-token   3      14m
````

This is not sustainable on the long term, I have a cluster that has been running for almost a year, with intensive usage (testing, etc) that creates and deletes a lot of resources. The ingress controller has created more that 100.000 secrets and is eating too much memory.

### Expected Behavior

Reuse exisitng secrets, and or delete obsolete secrets.

### Kong Ingress Controller version

```shell
v2.3
```

### Kubernetes version

```shell
kubectl version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:41:58Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5-gke.2400", GitCommit:"edad26ea7e78d44536b547193f30209b03e954c9", GitTreeState:"clean", BuildDate:"2022-04-15T09:31:56Z", GoVersion:"go1.17.8b7", Compiler:"gc", Platform:"linux/amd64"}
```

### Anything else?

Thank you!

**Comment by shaneutt** [comment]
Hi @Pixcell thanks for your report.

I created a `v1.23.5` cluster and deployed KIC `v2.3` and attempted to reproduce this, but so far I haven't been able to. I've monitored the secrets in all namespaces while I create and teardown `Ingress` resources as you described, but the count of `Secrets` doesn't change.

What else is interesting here is that we do not provide the ingress controller create permissions for `Secrets` by default:

```yaml
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
```

And furthermore the list of `Secrets` you provided look like the `Secrets` that the Kubernetes control-plane (not our ingress controller) would be creating to authenticate the `ServiceAccount`. Can you verify whether there are any failures or other problems going on in your cluster's control-plane that might account for this?

Otherwise would you be able to provide a contained reproduction of this issue with full steps to recreate inside a [Kind](https://github.com/kubernetes-sigs/kind) or [Minikube](https://github.com/kubernetes-sigs/minikube) cluster? Such a local reproduction would make it considerably easier to figure out what may be triggering this.

**Comment by Pixcell** [comment]
Hi @shaneutt 

Thank you for looking into this!
You might be into something regarding the ServiceAccount.
I'll investigate further and come back to you with an answer. Thank you for pointing this out, I am still learning the ins and out of kubernetes.

If this is not it, I'll figure out a way to reproduce this in a contained fashion for you to explore further.

**Comment by shaneutt** [comment]
> Hi @shaneutt
> 
> Thank you for looking into this! You might be into something regarding the ServiceAccount. I'll investigate further and come back to you with an answer. Thank you for pointing this out, I am still learning the ins and out of kubernetes.
> 
> If this is not it, I'll figure out a way to reproduce this in a contained fashion for you to explore further.

Sounds good :+1: we'll consider this closed then for the moment, but we will re-open this if you need. :vulcan_salute:
