### ISSUE TITLE
Ingress Controller tries watching non-existent resource type and eventually crashes

### ISSUE THREAD

**Issue by emrebasar** [Kong/kubernetes-ingress-controller#2563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When deploying Ingress Controller on a Kubernetes 1.18 cluster, even though the `IngressClass` support from `networking.k8s.io/v1` api version is disabled explicitly by setting `CONTROLLER_ENABLE_CONTROLLER_INGRESS_CLASS_NETWORKINGV1` flag to `true`, the Ingress Controller tries to watch those resources, which fails, and eventually causes the Ingress Controller shutdown due to cache population context getting timed out.

### Expected Behavior

Ingress Controller should either not try to watch the non-existent resources in the cluster, or use the alternative `IngressClass` resource with api version `networking.k8s.io/v1beta1` that exists in the cluster.

### Steps To Reproduce

```markdown
In a Kubernetes 1.18 cluster without support for `networking.k8s.io/v1` `Ingress` and `IngressClass` resources. Try deploying the Ingress Controller with following environment variables:


CONTROLLER_ENABLE_CONTROLLER_INGRESS_EXTENSIONSV1BETA1: "true"
CONTROLLER_ENABLE_CONTROLLER_SERVICE: "true"
CONTROLLER_ENABLE_CONTROLLER_INGRESS_NETWORKINGV1: "false"
CONTROLLER_ENABLE_CONTROLLER_INGRESS_CLASS_NETWORKINGV1: "false"
CONTROLLER_ENABLE_CONTROLLER_INGRESS_NETWORKINGV1BETA1: "false"
CONTROLLER_ENABLE_CONTROLLER_KNATIVEINGRESS: "false"
CONTROLLER_ENABLE_CONTROLLER_KONGCLUSTERPLUGIN: "false"
CONTROLLER_ENABLE_CONTROLLER_KONGCONSUMER: "false"
CONTROLLER_ENABLE_CONTROLLER_KONGINGRESS: "false"
CONTROLLER_ENABLE_CONTROLLER_KONGPLUGIN: "false"
CONTROLLER_ENABLE_CONTROLLER_TCPINGRESS: "false"
CONTROLLER_ENABLE_CONTROLLER_UDPINGRESS: "false"
CONTROLLER_LOG_LEVEL: "debug"
```
Check the error logs and you should see log lines originating from `controller-runtime` logger saying that kind `IngressClass` not found in api version `networking.k8s.io/v1`. The ingress controller should eventually shut down.

### Kong Ingress Controller version

```shell
2.3.1
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Anything else?

While going through the issues, I noticed that according to #1666 the support for Kubernetes < 1.19 is being phased out, but since it is still supported, this patch would enable setups without the opportunity to upgrade to continue using the Ingress Controller.

**Comment by rainest** [comment]
Do you have a copy of the controller-runtime logs in question? IIRC we no longer test on 1.19 because we can't get the KIND images for it to work anymore, so replicating it may be difficult. I wonder if it's something we'd want to address upstream--it seems like it'd make sense for controller-runtime to handle that more gracefully.

**Comment by rainest** [comment]
On further review, I think the simpler solution to this is probably adding a new boolean [controller configuration parameter](https://github.com/Kong/kubernetes-ingress-controller/blob/a15201d0045d62d7c87b1155357cb092e292b8c9/internal/manager/controllerdef.go#L97-L103), setting it to the IngressClass controller's enable flag's value, and then using it to control whether the [additional IngressClass watches](https://github.com/Kong/kubernetes-ingress-controller/blob/a15201d0045d62d7c87b1155357cb092e292b8c9/hack/generators/controllers/networking/main.go#L484-L491) that we use to trigger new reconciles as of https://github.com/Kong/kubernetes-ingress-controller/commit/d8a4d27ff6fdcfa012dec4b3cffaa5010ffe751c

@emrebasar if this doesn't occur on 2.2.1, that should more or less confirm that it's only the new watches from that change are the only problem ones, and that disabling them should clear the issue. I'd suggest that over https://github.com/Kong/kubernetes-ingress-controller/pull/2564 since on brief review it'd require more work to actually implement v1beta1 IngressClasses and we'll presumably proceed with #1666 in the not too distant future.

**Comment by emrebasar** [comment]
Hi @rainest, thank you for taking the time to look at this. I agree that the best solution for this would be at the controller-runtime level, as it would also prevent similar issues on other clusters with different configurations. Here is a snippet I got from the controller-runtime when I deployed version 2.3.1:

```
time="2022-06-13T09:10:33Z" level=error msg="if kind is a CRD, it should be installed before calling Start" error="no matches for kind \"IngressClass\" in version \"networking.k8s.io/v1\"" kind="{\"Group\":\"networking.k8s.io\",\"Kind\":\"IngressClass\"}" logger=controller-runtime.source
```
For adding the controller configuration parameter, it would absolutely solve the problem for our case. I wasn't sure if there was any other behavior dependent on having that feature always on. I tried deploying 2.2.1 and can verify that the error did not happen on that version.

**Comment by emrebasar** [comment]
Ok, thank you for the clarification. How would you like to proceed here? I can create a new PR with the boolean flag to enable/disable additional watching of `IngressClass` objects for example?

**Comment by rainest** [comment]
@emrebasar I created my own. I've uploaded a draft image (based on the [2.4.0 release](https://github.com/Kong/kubernetes-ingress-controller/blob/main/CHANGELOG.md#240)) with the changes from #2577 at `traines/kic:2.4.0-PR2577`. Can you test with that with `CONTROLLER_ENABLE_CONTROLLER_INGRESS_CLASS_NETWORKINGV1=false` to see if clears the issue?

**Comment by emrebasar** [comment]
Hi @rainest, yes, I can confirm that the error messages do not happen when using that version.
