### ISSUE TITLE
test(integration) integration tests with kong nightly build failed

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#2748]
Recent PRs are all failed on CI job `tests / integration-tests-enterprise-postgres-nightly`, which runs integration tests with nightly build images of Kong gateway. The failed cases are:
- `TestHTTPRouteEssentials` (failed at `httproute_test.go:203`)
- `TestHTTPSRedirect` (failed at `ingress_https_test.go:185`)
- `TestPluginEssentials` (failed at `plugin_test.go:{78,164,198}`)
- `TestPluginOrdering` (failed at: `plugin_test.go:{251,309,331,353}` )
- `TestIngressNamespaces` (failed at: `ingress_test.go:452`)
-  `TestIngressClassNameSpec` (failed at: `ingress_test.go:305`)
- `TestDefaultIngressClass` (failed at: `ingress_test:736`)
This would not be flakes, because many PRs failed at the same set of cases at the same place.
example runs: 
- https://github.com/Kong/kubernetes-ingress-controller/runs/7554682932?check_suite_focus=true
- https://github.com/Kong/kubernetes-ingress-controller/runs/7554835004?check_suite_focus=true
- https://github.com/Kong/kubernetes-ingress-controller/runs/7573857718?check_suite_focus=true
Does this mean that we should update KIC or its dependencies for operating kong gateway for kong 3.0?

**Comment by randmonkey** [comment]
From the logs in integration tests run for #2749, the reason why the tests failed is kong gateway returned 404. So we may further investigate on code for configuring Kong.

**Comment by rainest** [comment]
That it's _only_ nightly Kong failing suggests that maybe that image is more prone to breakage in fundamental routing behavior than I'd expected. It ran successfully when initially added, then stopped, and I think there's a decent chance upstream introduced a bug that they haven't fixed yet. The nightly OSS image similarly broke tests because of an upstream bug (and, in their case, it was a fixed bug whose fix wasn't available because the images weren't being updated).

We may want to move the Kong nightly tests to a dispatch workflow and/or a cron workflow instead of running it on each PR. We mostly care about it for code that introduces 3.0-only features and catching incompatibility with existing behavior, and I wouldn't expect most PRs to make previously 3.0-compatible controller functionality suddenly incompatible. Compatibility testing may unfortunately just be iffy until the 3.0 images are RC quality.

These are generally proxy behavior tests (where we're actually sending a request and seeing if it routes), so my best guess is that the flakes are the result of some other test running concurrently and creating overlapping configuration (we use `/httpbin` routes quite often, for example--two of those tests will produce different results when they do/do not run concurrently). To that end, I want to capture a snapshot of the configuration so I can restore it and inspect it and manually send requests outside CI using https://github.com/Kong/kubernetes-testing-framework/pull/334. I think it will usually be difficult to determine the cause from response codes alone.

**Comment by pmalek** [comment]
I'd like to highlight the fact that despite us wanting to test KIC with nightly images of GW, we shouldn't strive to be obsessive about 100% of tests passing at all times when deploying KIC in such a scenario.

We have enough variance and flakiness within our setup and despite the fact that those tests against GW nightlies should be run in general, as @rainest suggested they shouldn't run against each PR. Ideally those should be somehow explicitly labelled as "allowed to fail" (with a reason also mentioned somewhere).

**Comment by shaneutt** [comment]
> I'd like to highlight the fact that despite us wanting to test KIC with nightly images of GW, we shouldn't strive to be obsessive about 100% of tests passing at all times when deploying KIC in such a scenario.

Correct. It's a nightly image, there will be things out of our control. Occasionally things will just be flat out broken.

> We have enough variance and flakiness within our setup and despite the fact that those tests against GW nightlies should be run in general, as @rainest suggested they shouldn't run against each PR. Ideally those should be somehow explicitly labelled as "allowed to fail" (with a reason also mentioned somewhere).

Agreed.

**Comment by pmalek** [comment]
One more comment: I do realize that it's hard to make e2e tests (that include components that we're cannot fully rely on) 100% reliable but having tests like these run against each PR and being red for 90% of the time will just leave a mark in our brains saying: "Those are OK to fail, don't bother looking at these failures, it's fine" which will basically nullify the whole effort.

**Comment by shaneutt** [comment]
> One more comment: I do realize that it's hard to make e2e tests (that include components that we're cannot fully rely on) 100% reliable but having tests like these run against each PR and being red for 90% of the time will just leave a mark in our brains saying: "Those are OK to fail, don't bother looking at these failures, it's fine" which will basically nullify the whole effort.

Historically it has been very rare that a test failure for 3rd party components failed for reasons other than something wrong with our testing code, so I'm not sure I'm ready to go along with this. But I'm also not exactly sure what this is and what action this comment is pursuing.

**Comment by pmalek** [comment]
I was trying to comment that failing test jobs (like recently e.g. [integration-tests-enterprise-postgres-nightly](https://github.com/Kong/kubernetes-ingress-controller/runs/7614033500?check_suite_focus=true#logs)) after failing for a while are "OK" and become white noise that we got used to. So basically I'd try us to pursue tests reliability, to a degree that we're (almost) certain that when we see a failure in CI it's a failure which we need to act upon not a spurious CI/runner/network/dependency failure that all we can do is re-run (or worse: do nothing).

**Comment by shaneutt** [comment]
> I was trying to comment that failing test jobs (like recently e.g. [integration-tests-enterprise-postgres-nightly](https://github.com/Kong/kubernetes-ingress-controller/runs/7614033500?check_suite_focus=true#logs)) after failing for a while are "OK" and become white noise that we got used to. So basically I'd try us to pursue tests reliability, to a degree that we're (almost) certain that when we see a failure in CI it's a failure which we need to act upon not a spurious CI/runner/network/dependency failure that all we can do is re-run (or worse: do nothing).

Ah ok, that makes more sense. I'm with you entirely on this motive. This is where we were at late last year and early this year, and where we need to get back to.

**Comment by mflendrich** [comment]
Closed - stale
