### ISSUE TITLE
Spike: Knative Integration Maturity

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#2813]
### Problem Statement

Historically we've not had a lot of feedback, requests or known usage regarding our [Knative](https://knative.dev) integration and so it's been a question what the value of continuing to maintain it is. There's a fair amount of code wrapped up in it, and we've also had a fair amount of times where upstream has broken something which caused failures in our integration and e2e tests, so it's incurred some significant maintenance costs. The purpose of this task is to assess and build consensus among the maintainers about what we want to do with the future of this integration.

### Proposed Solution

Either:

- [ ] we decide that we want to keep Knative support: write a KEP describing the key features and a graduation criteria that defines how we intend to move the integration from it's current maturity level of alpha, to beta and eventually GA

OR:

- [x] we pull the integration entirely and remove the code as part of a major release, to significant reduce our maintenance costs.

### Acceptance criteria

- [ ] KIC's feature gates docs are updated at
  - [ ] https://docs.konghq.com/kubernetes-ingress-controller/latest/references/feature-gates/#feature-gates-for-alpha-and-beta-features
  - [x] in tree feature gates doc is updated https://github.com/Kong/kubernetes-ingress-controller/blob/edfd7e2b1c2f7e2b9866c3ca7dd08c956a4a0866/FEATURE_GATES.md#L58-L59

**Comment by mflendrich** [comment]
@pmalek pointed out that knative is behind a default-true feature flag. The action to perform could be disabling the feature flag by default, and then removing if we don't see usage out in the wild.

Suggestion: flip the default to false in 2.9, and (if we see little use of this feature flag), drop the code paths altogether in 3.0.

**Comment by martinkubrak** [comment]
For what it's worth, we are using KIC and are in the process of implementing knative. We do need a uniform auth process across our deployments (both 'normal' k8s deployments and knative) so if KIC drops knative support we probably would have to replace Kong with something else.

**Comment by shaneutt** [comment]
> For what it's worth, we are using KIC and are in the process of implementing knative. We do need a uniform auth process across our deployments (both 'normal' k8s deployments and knative) so if KIC drops knative support we probably would have to replace Kong with something else.

We appreciate you sharing, feedback about our knative integration has been sorely missing, which is why this issue even exists. Are you able to share any more details about your use case and the context around which you use it? Details like how many routes you handle with it, and what kind of product you're building with it (if applicable) would be appreciated as today we have extremely limited insights into usage in the wild.

**Comment by martinkubrak** [comment]
@shaneutt we are in the process of evaluating knative. We use Kong Ingress Controller for 'native' k8s apps (mainly for authentication) so using it for knative makes the most sense for us. After spending some time playing around with knative and Kong, I think we could work around lack of native support for it. This is mainly because we would need path-based access to our knative workloads anyway, and my understanding is we can easily achieve that with `Ingress` + `request-transformer` plugin.

**Comment by mflendrich** [comment]
Thank you for your feedback @martinkubrak. I'm putting this issue in the KIC v3.0 milestone so that we can define our path forward in the next major release.

**Comment by rainest** [comment]
Was https://github.com/Kong/kubernetes-ingress-controller/issues/2813#issuecomment-1290868573 actually true? It doesn't look like we've had the feature flag default true since the addition of feature gates:

```
13:38:58-0700 esenin $ git grep -E "KnativeFeature:\s*false" $(git rev-list --all) | wc -l
380
13:39:42-0700 esenin $ git grep -E "KnativeFeature:\s*true" $(git rev-list --all) | wc -l 
0
```

We did have it mistakenly [placed behind the GWAPI gate](https://github.com/Kong/kubernetes-ingress-controller/commit/6fae6cb35b7eab89d480595aaf885574dffc8d6a#diff-deb797d687c689054f4453f9270f13d4bc05ae5447b31c01829768fe168e572bR257) until 2.6. Since the feature gate isn't actually on, it looks like it's been disabled for much longer than we thought.

A reports search for any instance that has enabled it turned up nothing after about 4M records (previous month search--it doesn't show the final count searched for whatever reason), so it does not appear anyone has flipped it on. We should mark it deprecated and plan to remove it sooner rather than later.

**Comment by dark-m0de** [comment]
@rainest - One question: Would you change your mind about "marking Knative support deprecated" in case we do an upstream contribution to fix the issue?

I can't promise anything. However, I have a skilled GoLang developer in the team that could have a look at it. It's just that I don't want to spend the time for something that is going to be deprecated afterwards.

**Comment by rainest** [comment]
@dark-m0de it's more a question of overall maintenance burden over time weighed against actual usage than any single bug. The status of #2543 wouldn't really sway the decision either way.

**Comment by programmer04** [comment]
Other related issues
- https://github.com/Kong/kubernetes-ingress-controller/issues/4442

**Comment by pmalek** [comment]
Support for Knative has been removed in #4748 and is planned to be released in 3.0.0

**Comment by rainest** [comment]
AFAIK there's no reason to keep this open further after #4748. Please reopen if we know of something else we need to do prior to the 3.0 release.

**Comment by pmalek** [comment]
We can leave this at the very least to track the docs feature gates update: https://docs.konghq.com/kubernetes-ingress-controller/latest/references/feature-gates/#feature-gates-for-alpha-and-beta-features

**Comment by mflendrich** [comment]
> We can leave this at the very least to track the docs feature gates update: https://docs.konghq.com/kubernetes-ingress-controller/latest/references/feature-gates/#feature-gates-for-alpha-and-beta-features

Handled in https://github.com/Kong/kubernetes-ingress-controller/issues/4961 - closing this issue in favor of that one.
