### ISSUE TITLE
Document the intention to delete KongIngress support for Gateway API

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#3020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

We don't want to support KongIngress together with Gateway API routes, but certain KongIngress features aren't available in GW API today.

### Proposed Solution

Clearly document the intended dynamic: explicitly and effectively disable support for KongIngress features in conjunction with GW API routes (and suggest ways to do KongIngress things with pure Gateway API) to give the user base possibility to migrate easily

### Acceptance Criteria

- [ ] KIC docs say that KongIngress support in GW API is deprecated & expected to be disabled in KIC 3.0.

**Comment by rainest** [comment]
This is iffy without https://github.com/Kong/kubernetes-ingress-controller/issues/2941 since some of those features have no migration path yet (GWAPI has indicated they don't intend to support standard APIs for things like connection timeouts, and those don't have annotations yet--ironically because we originally thought GWAPI _was_ going to add them).

This would further imply that we do remove KongIngress entirely and replace it with KongUpstream for upstream configuration outside the basic weighting offered by GWAPI standards. Some of those settings (`hash_on`, for example) are single KV pairs and could fit in annotations, but others (anything involving healthchecks) definitely do not.

**Comment by mflendrich** [comment]
Preferred location for this warning (@rainest's idea):
- KongIngress reference
- KongIngress guide
- Changelog (the list of supported features for KongIngress)

**Comment by rainest** [comment]
https://github.com/Kong/docs.konghq.com/pull/4894 adds the guide note only. https://github.com/Kong/docs.konghq.com/pull/4813 is responsible for the Reference blurb, and now includes one.

Ended up not putting anything in the GWAPI support page since there's no functional effect. The only thing that still requires a KongIngress is some upstream configuration, and that only applies to Services, not any routing resource.

**Comment by rainest** [comment]
https://github.com/Kong/docs.konghq.com/pull/4813 is now in.

https://github.com/Kong/docs.konghq.com/pull/4894 is still pending but we're probably fine to release without it. There's no immediate need to have this right at release.

**Comment by pmalek** [comment]
@rainest Is this resolved already?

**Comment by rainest** [comment]
With 4894 merged this is done, yes.
