### ISSUE TITLE
Kong Leader election failure causing all pods to restart at the sametime 

### ISSUE THREAD

**Issue by ammartins** [Kong/kubernetes-ingress-controller#3124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.8

### Current Behavior

We run kong in Kubernetes with a PSQL database, and since a few versions, we noticed lots of issues with Kong Leader election.

Usually, kong would use a config map and set up the leader pod, and we see that the API calls to check for leaders are huge.

In 30 minutes we see 15K calls to /apis/coordination.k8s.io/v1/namespaces/<>/leases/kong-ingress-controller-leader, and from time to time (normally around 48hours) all pods restart because the lease to configmap can't be done.

### Expected Behavior

Leader pod elections should not be checked 15k times in 30 minutes, and if a timeout occurs should retry not restart all pods at once. Leader.

### Anything else?

```
```
16; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.79 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/383.1.0.25.106;]"
2022/09/15 09:32:07 [notice] 1#0: signal 3 (SIGQUIT) received from 1273, shutting down
2022/09/15 09:32:07 [notice] 1111#0: gracefully shutting down
2022/09/15 09:32:07 [notice] 1110#0: gracefully shutting down
2022/09/15 09:32:07 [crit] 1111#0: *2210 [lua] targets.lua:248: could not reschedule DNS resolver timer: process exiting, context: ngx.timer
[11:39](https://rtlnederland.slack.com/archives/GCRP7PK28/p1663234740710389)
E0914 22:13:11.297417       1 leaderelection.go:330] error retrieving resource lock api-gateway/kong-ingress-controller-leader-kong: Get "[https://10.122.0.1:443/apis/coordination.k8s.io/v1/namespaces/api-gateway/leases/kong-ingress-controller-leader-kong](https://10.122.0.1/apis/coordination.k8s.io/v1/namespaces/api-gateway/leases/kong-ingress-controller-leader-kong)": context deadline exceeded
I0914 22:13:11.297498       1 leaderelection.go:283] failed to renew lease api-gateway/kong-ingress-controller-leader-kong: timed out waiting for the condition
Error: leader election lost
Error: leader election lost
``` 
```

**Comment by rainest** [comment]
Moved to the KIC repo since this is entirely within the controller.

@ammartins are you seeing issues with your API server response times? They appear to be the cause based on review of the code. Ultimately, we don't control much of leader election behavior, as we import standard Go libraries for leader election in Kubernetes. We probably can, at most, expose options increasing the timeout, but that'd be a bandage over the still-present issues with API server response times. API server slowness will likely cause issues throughout the controller (and other applications in the cluster), so you would want to address it.

The log

```
I0914 22:13:11.297498 1 leaderelection.go:283] failed to renew lease api-gateway/kong-ingress-controller-leader-kong: timed out waiting for the condition
```
is from [the client-go leader election utility attempting to retrieve the ConfigMap](https://github.com/kubernetes/client-go/blob/v12.0.0/tools/leaderelection/leaderelection.go#L321-L326) and getting no response within the timeout. That timeout is set by the [controller-runtime manager](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.13.0/pkg/manager/internal.go#L608-L648).

We do not set or expose the [RenewDeadline setting](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Options) that controls that timeout or any of the related options, so you should see each Pod check the leader state every 15 seconds with a 10-second timeout and a 2-second wait between retries if the check fails. The check count you're observing may not be that unusual if you have a lot of replicas and they're all stuck retrying (a single Pod retrying over the entire half hour should check 900 times).

Leader election losses do [restart the leader](https://github.com/kubernetes-sigs/controller-runtime/blob/c2f04bb7d9095acc62bbd571f5a9a94ab05c79e8/pkg/manager/internal.go#L633-L636) (I'm guessing it's not easy to terminate all the processes that start on the leader otherwise), but won't restart others. You may, however, be seeing something where many Pods are becoming the leader, failing to update their lease, and then terminating in succession after another Pod grabs it.
