### ISSUE TITLE
`ingressV1ToKongServiceLegacy()` using `%d%d` for route names which might cause 2 different routes indistinguishable

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#3942]
It seems that creation of `kong.Route`s uses `%d%d` for route names which might cause 2 different routes indistinguishable

So e.g. there won't be any distinction between `i=1`,`j=11` `i=11`,`j=1`

_Originally posted by @pmalek in https://github.com/Kong/kubernetes-ingress-controller/pull/3939#discussion_r1179614942_

**Comment by programmer04** [comment]
The described problem occurs in two places

- https://github.com/Kong/kubernetes-ingress-controller/blob/88651c84ae0ed88dc28272077e49a17adbda1056/internal/dataplane/parser/translate_ingress.go#L160

- https://github.com/Kong/kubernetes-ingress-controller/blob/88651c84ae0ed88dc28272077e49a17adbda1056/internal/dataplane/parser/translate_knative.go#L76

Since we're going to support only combined routes and want to ditch support for Knative, see
- https://github.com/Kong/kubernetes-ingress-controller/issues/4160
- https://github.com/Kong/kubernetes-ingress-controller/issues/2813

Does it make this issue obsolete and can be closed?

**Comment by programmer04** [comment]
Merging 
- https://github.com/Kong/kubernetes-ingress-controller/pull/4749
- https://github.com/Kong/kubernetes-ingress-controller/pull/4748

removed all mentions of `%s.%s.%d%d` so issue is resolved.

But the issue is still presented in KIC `2.12`that is planned to be supported for quite some time

**Comment by mflendrich** [comment]
Leaving with the desired scope of fixing this in KIC 2.12.
