### ISSUE TITLE
Remove `dbless-combined-services` from integration tests matrix

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#3979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

When `CombinedServices` becomes enabled by default, there's no need for a separate entry in the integration tests matrix. #3777 is to be released in 2.10.0 and according to our policy for its lifetime, it should be enabled by default in the next minor release, which most probably will be 2.11.0.

### Proposed Solution

Remove the `dbless-combined-services` entry from `.github/workflows/_integration_tests.yaml`.

### Acceptance Criteria

- [ ] No redundant integration tests are run for `CombinedServices` feature gate

**Comment by rainest** [comment]
We are indeed flipping the toggle for 2.11 then, correct?

Completing this would imply that we have done so, but there was no blocking issue associated with this even though it's marked ready.

I created a PR to do both the toggle and remove the test since it seems that's likely the case, but if we still need to decide if the change will go into 2.11 we need a separate issue or amendments to this one.

**Comment by czeslavo** [comment]
@rainest I think that flipping to default true in 2.11 is according to our agreement about the gradual introduction of this feature. I'd just confirm with @mheap?

**Comment by mheap** [comment]
Default true in 2.11 is fine with me. This does change metric names, but there is a way to disable it that we should document
