### ISSUE TITLE
Prometheus metric with lock-up/translate error status

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#4004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

KIC's node agent reports the red/amber/green status: https://github.com/Kong/kubernetes-ingress-controller/blob/420f02a162b83ae5c1371840859a7826e10cf263/internal/konnect/nodes/types.go#L54-L56

We could create a Prometheus metric with equivalent information.

### Proposed Solution

A new Prometheus metric added that one can configure an alert on in case of:
- lock-up
- no lock-up, but translation errors appearing

### Acceptance Criteria

- [ ] As a k8s platform engineer, there is a Prometheus metric I can set up alerts on if a lock-up is ongoing
- [ ] As a k8s platform engineer, there is a Prometheus metric I can set up alerts on if translation errors are happening in the current config

**Comment by rainest** [comment]
We already have these in the form of https://github.com/Kong/kubernetes-ingress-controller/blob/f1b345b33ab7fc8233f6df09242f3d0c273aa0e7/internal/metrics/prometheus.go#L82-L113, correct? It's kinda wonky since it's a counter that marks each tick as successful or failed, but there's [no obvious perfect alternative](https://prometheus.io/docs/concepts/metric_types/) to just represent the current status.

Alerting should be able to fire if either metric's success key matches `false` for more than a minute fine.

**Comment by rainest** [comment]
From review again after a meeting discussion, we do still kinda have this already, and the existing metrics do satisfy the acceptance criteria. However, we do record them _differently_ than the node agent does, and we're a bit hamstrung if we want to make it exactly the same as the node agent.

Meeting discussion indicated that the existing Prometheus translation metric only tracked catastrophic failures, but that's not actually the case.  `parser.BuildKongConfig()` actually doesn't have a catastrophic failure case, and can only return a collection of per-resource translation failures. Both Prometheus and agent metrics collapse this into a single "translation error count > 0" metric:
- Prometheus records a TranslationCount tick with `Success=false`
- Node agent sets a TranslationErrorHappened/IngressControllerStatePartialConfigFail/yellow status unless there's also a push failure.

Similarly, they both track push failures/lockups:
- Prometheus records a ConfigPushCount tick with `Success=false`
- Node agent records an ApplyFailed/IngressControllerStateInoperable/red status. This supersedes yellow status.

Node agent masking translation failures if there are push failures is a bit misleading: both can occur concurrently, from different resources. You could, for example, have some Ingress with a missing service that gets omitted from configuration (a translation failure) while you simultaneously have a successfully-translated TCPIngress that tries to set `strip_path` (an invalid route that will lead to a push failure). However, we may consider the latter error masking the former desirable, because the lockup requires more urgent attention.

- Combining the two Prometheus metrics into a single metric that either has a `ConfigState=Success/PartialSuccess/Failure` metric or separate labels for translation and push success would be a breaking change. 
- An additional metric with the above state label would not be breaking, but would be redundant.
- Adding the above state label to one of the existing metrics is a bit annoying. We [record translation failures](https://github.com/Kong/kubernetes-ingress-controller/blob/c3b9f35cd83d004d1fdeb374ab4e3d361f4877ef/internal/dataplane/kong_client.go#L366-L371) before we attempt to push, and [record push failures](https://github.com/Kong/kubernetes-ingress-controller/blob/c3b9f35cd83d004d1fdeb374ab4e3d361f4877ef/internal/dataplane/sendconfig/sendconfig.go#L90-L94) in a different level of the call stack and include info that we don't return, so we'd have to plumb the translation failure info down to it.

So I'd say that we should probably avoid that unless we really want the presentation to match. If being able to alert on either case is the main goal, that's already possible.

We do lack gauge metrics for either failure type--I think the addition of metrics predates our tracking counts of both types of errors, and those are arguably of more interest than the cycle counts that we currently have, so I can add those as an alternative.
