### ISSUE TITLE
Consumer groups staged delivery

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#4411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

- [ ] ~Consumer group support is hidden behind a default-off feature gate~ (on team sync decided to skip feature-gating)
- [ ] ~Consumer group behavior provides a graceful failure mode if used with a Gateway version that does not support consumer groups yet~ (see https://github.com/Kong/kubernetes-ingress-controller/issues/4411#issuecomment-1656243151)
- [x] Dependency: Ensure that deck has https://github.com/Kong/deck/pull/959 implemented
- [x] Ensure usage of Kong Gateway 3.4 in the integration test for Consumer Groups
               - allow running integration tests on demand with the latest Kong Gateway image https://github.com/Kong/kubernetes-ingress-controller/pull/4469

### Proposed Solution

ensure that the consumer group support in KIC 2.11 takes care of all the above

### Acceptance Criteria

- [x] all the boxes above are checked

**Comment by rainest** [comment]
Continued from https://github.com/Kong/kubernetes-ingress-controller/pull/4419#pullrequestreview-1551180064 we normally don't have version-dependent (or Enterprise-dependent) handling for features that are simply absent in some Kong releases. We can reasonably expect users to follow documentation for their versions and not attempt to use unavailable features, and throwing a config error in the event they don't is fine--it's not ideal because of the all-or-nothing nature of config applies, but at least visible.

If we do add additional protections for these, we should only add them to the webhook and not have the parser drop them silently. The latter isn't readily visible, as your config would be "accepted" but not actually take effect. You'd need to dig through logs to find any indication of the issue, and likely wouldn't know exactly what to look for.

We did add such skips often in the past, but apply errors also used to be more catastrophic because there was no good means of tracing them back to their cause.

Webhook rejections, by contrast, are immediately visible at apply time and have the same end effect (config isn't broken). We can use them here as neither requires cross-resource checks: we can reject a KongConsumerGroup resource outright, and can reject any non-empty `consumerGroups` field if the version isn't compatible.

Skipping invalid config _may_ be appropriate when KongConsumers reference non-existent groups, since that would require cross-resource lookups and thus can't be checked in the webhook. However, I'd still lean towards allowing the failures, since these should either be a case of waiting for eventual consistency (in which case you keep running with old config briefly, but successfully transition to an up-to-date one once resources settle) or a case where you actually need to fix something to get the config you want (e.g. you typo the name and don't actually get active config for that consumer).

We should probably also work to surface any skips as conditions rather than logs, since those are visible on the affected resources, and we can provide kubectl filters for them.

---

Aside that, I'm not sure how error Event generation handles unknown resource types. I think adding the field under a consumer should still bind to a KongConsumer, but I suspect creating a KongConsumerGroup and adding the independent entity won't correctly bind to the causing resource--I would be surprised if Kong can attach the tags to the error in that case. We probably do have room for improvement there.
