### ISSUE TITLE
Support `TLSRoute` with expression router

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#4540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Split out of https://github.com/Kong/kubernetes-ingress-controller/issues/4312
Kong 3.4 added support of expression router in L4 proxy. We could implement support of TLSRoute in gateway APIs.

### Proposed Solution

- Translate TLSRoute into expression based Kong route when ExpressionRoutes feature gate is enabled, and Kong uses expression router

### Acceptance Criteria

- [ ] KIC could translate TLSRoute to expression based Kong routes against Kong 3.4+ running with expression router
- [ ] TestTCPIngressTLSPassthrough works as well.

**Comment by rodman10** [comment]
\assign

**Comment by randmonkey** [comment]
assigned to @rodman10

**Comment by rodman10** [comment]
When I was trying to implement tls expression route, I found tls route only matched with `destination port`, and without `sni`.
![image](https://github.com/Kong/kubernetes-ingress-controller/assets/16054053/95a99c9c-59f3-4c72-8c3e-c4d5d59a3efa)
So the tls expression need `dst.port` field only? @randmonkey

**Comment by rainest** [comment]
Piggybacking the TCPIngress TLS passthrough on this. TCPIngress otherwise works in https://github.com/Kong/kubernetes-ingress-controller/pull/4612 and the issue with passthrough not matching will presumably have the same fix for both TLSRoute and TCPIngress.

**Comment by rainest** [comment]
This requires a gateway change: https://github.com/Kong/kong/pull/11538

Our implementation isn't expected to change. We [add expression SNI criteria if the route object contains traditional SNI values](https://github.com/Kong/kubernetes-ingress-controller/blob/ba84ae34154bffde5eda32040b9aab360f255808/internal/dataplane/parser/translators/l4route_atc.go#L15) already.

TLSRoute will require removing [the not supported abort](https://github.com/rodman10/kubernetes-ingress-controller/blob/7a0bd0f474e8e7ce51ce6522d99131ddaf5fc4fc/internal/dataplane/parser/translate_tlsroute.go#L32-L34).

TCPIngress with TLS passthrough already creates routes that will match after the fix following #4612, and will only require enabling the tests.

Dunno how we want to handle this for 2.12, since I don't expect the gateway fix to be released by then. We could add the functionality anyway without enabling tests with the expectation that it will work on a fixed gateway release.
