### ISSUE TITLE
`KongPlugin` support for Kong secrets management ("vaults") - just the default vault

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#4558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Some users will want to extract the sensitive parts of their plugin configs to an external vault. Gateway already has such capabilities (https://docs.konghq.com/gateway/latest/kong-enterprise/secrets-management/)

### Proposed Solution

A documented way to create `KongPlugin` configs that reference values from a Kong vault exists.

### Acceptance Criteria

- [x] Support for vaults is verified to work and any missing functionality in KIC is identified and implemented
- [ ] A guide describing how to use Kong secrets management with KIC exists

**Comment by rainest** [comment]
Nothing is needed to support this. Plugins use magic strings to obtain values from Kong vaults, so you just dump that string into a compatible field under `config`: 

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: http-log-example
plugin: http-log
config:
  flush_timeout: 2
  http_endpoint: '{vault://env/secret-http-endpoint}'
  keepalive: 1000
  method: POST
  retry_count: 15
  timeout: 1000
```

[vault-plugin.tar.gz](https://github.com/Kong/kubernetes-ingress-controller/files/12424198/vault-plugin.tar.gz) has a more complete example environment and usage. End confirmation is that proxy logs show:

```
2023/08/24 00:16:23 [warn] 2315#0: *183 [kong] queue.lua:195 [http-log plugin 162c74f7-2083-5f80-87c0-0ab278d31955] queue http://localhost:9999/fake:POST:application/json:1000:1000:15: handler could not process entries: failed request to localhost:9999: connection refused, context: ngx.timer
```
so it did extract that field from the environment.

We could potentially add something to https://docs.konghq.com/kubernetes-ingress-controller/2.11.x/guides/using-kongplugin-resource/ but there's not much to document beyond saying "put the string in the field"--it'd basically be the same demonstration as above.

We're unfortunately [limited in which field allow references](https://docs.konghq.com/gateway/latest/kong-enterprise/secrets-management/#referenceable-plugin-fields), and they're largely things that don't lend themselves to simple demos because they're mostly auth credentials or other configuration for external systems that you'd have to set up. The above "peek in logs to find an error" example works to confirm it works, but looks silly in documentation.

We could add vault config to, say, https://docs.konghq.com/kubernetes-ingress-controller/2.11.x/guides/redis-rate-limiting/ (we'd need to create the Redis user), but that's not great for discovery.

**Comment by mflendrich** [comment]
The (net new) guide I had in mind was "get from state zero to a functioning Vaults configuration with an example plugin".

**Comment by rainest** [comment]
Well, not really new, since it'd otherwise basically clone an existing doc, but there's a ToC entry (and intro copy) that pretends it's new!
