### ISSUE TITLE
Webhook warns if Ingress sets ingress class in annotation (instead of `.spec.ingressClassName`)

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#4791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Inspired by #4782.

We can make the validating webhook for `Ingress` issue a kubectl warning if the user tries to configure ingress with the annotation that has been long deprecated.

On the other hand, we would break plenty of guides that circulate on the internet if we made the migration a hard blocker.

### Proposed Solution

Add a validating webhook for `Ingress` that says something along the lines of

_The `kubernetes.io/ingress.class` annotation is deprecated and will be removed in a future version. Set the `.spec.ingressClassName` field instead._

### Acceptance Criteria

- [ ] the annotation still works but emits a warning when `kubectl apply`ing
- [ ] both the changelog and the webhook warning say clearly that support for the annotation will be removed in an (unspecified) future version

**Comment by programmer04** [comment]
Kubernetes out-of-the-box prints the warning for this
```
W1016 21:25:56.431536   66572 warnings.go:70] annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
```
the code was added 7 months ago to K8s

```go
_, annotationIsSet := ingress.Annotations[annotationIngressClass]
if annotationIsSet && ingress.Spec.IngressClassName == nil {
	warnings = append(warnings, fmt.Sprintf("annotation %q is deprecated, please use 'spec.ingressClassName' instead", annotationIngressClass))
}
```
[src - K8s repo](https://github.com/kubernetes/kubernetes/blob/3a3dc870a24645bb7114c0217aa743bd10c6122e/pkg/registry/networking/ingress/strategy.go#L104-L107).

I suggest leaving it as it is and not implementing a message in webhook. Covering that behavior with a test may be a little beneficial, but it's not so straightforward, because it requires setting [WarningHandler](https://pkg.go.dev/k8s.io/client-go/rest#Config.WarningHandler) in `*rest.Config` to capture warning messages emitted by K8s
