### ISSUE TITLE
New Topic: TLS Offloading Service Configuration

### ISSUE THREAD

**Issue by Rajakavitha1** [Kong/kubernetes-ingress-controller#4945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Requested by @mflendrich 

How to do TLS termination using Gateway API resources    

### Acceptance Criteria

* Provide instructions how to do TLS termination using Gateway API resources
* Instructions may be provided as a response to this issue and @Rajakavitha1 will port to the WIP KIC 3.0 branch in docs

**Comment by rainest** [comment]
https://gateway-api.sigs.k8s.io/guides/migrating-from-ingress/#tls-termination and https://gateway-api.sigs.k8s.io/guides/tls/#clientserver-and-tls are the major upstream docs for understanding the Gateway API TLS model. We should link these.

https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.Gateway (the conformance profile bit under the Listener section) and https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.TLSModeType are additional references that we probably do not need to link to.

In brief, TLS termination or passthrough in GWAPI  are configured via a combination of a Gateway's `listeners[].tls.mode` and the attached route type:

- `Passthrough` mode listeners inspect the TLS stream hostname via server name indication and pass the TLS stream unaltered upstream. These listeners do not use certificate configuration. They only accept TLSRoutes.
- `Terminate` mode listeners decrypt the TLS stream and inspect the request it wraps before passing it upstream. They require certificate [Secret reference](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.SecretObjectReference) in the `listeners[].tls.[]certificateRefs` field. They accept HTTPRoutes, TCPRoutes, and GRPCRoutes (presumably--the doc doesn't mention GRPCRoutes, but likely because GRPCRoute was added the TLS sections were originally written: https://github.com/kubernetes-sigs/gateway-api/pull/2518).

**Comment by lahabana** [comment]
Doone https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/services/tls/#tls-termination
