### ISSUE TITLE
New Topic: HA of KIC and GW

### ISSUE THREAD

**Issue by Rajakavitha1** [Kong/kubernetes-ingress-controller#4948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

As a user, I'd like to deploy KIC + Kong Gateway in a highly available way    

### Acceptance Criteria

* Provide instructions how to deploy KIC + Kong Gateway in a highly available way
* Instructions may be provided as a response to this issue and @Rajakavitha1 will port to the WIP KIC 3.0 branch in docs

**Comment by pmalek** [comment]
For the KIC part:

- HA Deployment is basically understood in kubernetes world (simplifying a little bit) as deploying with multiple replicas with leader election enabled.
- In KIC leader election setting is handled by the user and the logic is as follows:
  - if the `--konnect-sync-enabled` is enabled, LE (leader election is on)
  - if running in dbless mode and [Gateway Discovery](https://docs.konghq.com/kubernetes-ingress-controller/latest/concepts/deployment/#gateway-discovery) is enabled (through `--kong-admin-svc`) the LE is on
  - if running in DB backed mode, LE is on
  - otherwise, LE is disabled

**Comment by mheap** [comment]
To be explicit:

The user can scale their controller deployment to multiple pods and they'll automatically elect a leader?

**Comment by pmalek** [comment]
> To be explicit:
> 
> The user can scale their controller deployment to multiple pods and they'll automatically elect a leader?

Given the above mentioned rules : yes. The first one to be created will get the leader lease (given no other instances held it before) and all others that get created after that point will wait to get the lease

**Comment by rainest** [comment]
To preface, high availability in distributed systems generally does not lend itself to a one size fits all model: the strategy chosen will vary considerably depending on the failure domains you wish to account for, the topology of interconnect applications and underlying infrastructure, and your desired balancer between cost and resilience. We can describe the failure characteristics of our products and note general concepts you should be familiar with, but can't provide a complete design.

This topic is also quite large, so I'm not trying to cover it all at once.

## Cluster topology design for high availability

### Spreading workloads across failure zones

Production Kubernetes clusters should have multiple kubelets deployed such that they are not all likely to go offline or lose WAN connectivity all at once. For example, with cloud providers, this will typically mean spreading instances over multiple [availability zones and, for greater resilience, multiple regions](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html) to provide highly-available infrastructure. You must then instruct Kubernetes to [distribute workloads across this infrastructure](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) to ensure that you don't accidentally assign every proxy Pod to a single kubelet.

The charts provide [points to set topology constraints](https://github.com/Kong/charts/blob/kong-2.30.0/charts/kong/values.yaml#L860-L870) and other scheduler hints.

### Distributing dependencies across failure zones

Neither Kong nor the controller are particularly useful on their own. Their function relies on being able to interact with other applications in the cluster. Broader high availability thus requires both distributing individual workloads across infrastructure failure domains and ensuring that the other applications they interact with are also similarly distributed.

#### Controller/API server

The controller cannot update configuration if it cannot talk to the Kubernetes API, and will lose leader elections if it cannot talk to the API server long enough. You should therefore try to design topology constraints such that there will be an API server replica available to the controller.

#### Kong/upstream applications

Kong cannot do much of interest if it cannot talk to the upstream applications it proxies. If you design topology constraints such that Kong is highly available, but an upstream application only has two replicas in a single AZ, your Kong instances in other AZs will happily try and fail to route requests to the upstream application if the application's AZ goes down. You should therefore design application topology such that it will generally also be available to locations your proxy instances are running.

Application availability requirements will vary, and you will probably configure them with different levels of availability. For example, a critical application you wish to have online as much as possible may receive enough replicas and topology configuration such that it runs in every zone of your cluster, whereas a batch processing application whose requests can queue and be processed later may only be configured for one or two zones. Kong will be less likely able to process requests for the latter during an outage, but that's okay if the application's clients have time-insensitive workloads and know to retry.

#### Kong/controller

This section considers DB-less considerations. DB-backed considerations are more complicated and IDK if we want to address them, since we're encouraging the former.

Kong requires the controller provide it configuration to route requests. Although an existing Kong instance will keep its configuration in the event the controller goes offline, new Kong instances will not have configuration and will not become ready. This can have catastrophic effects if you need to scale your Kong instances or if the outage takes a large number of your existing proxy instances offline as well, overloading the remainder.

You should therefore distribute controller replicas to any zone where Kong proxy replicas exist. You will, however, use fewer controller replicas, as a single controller replica is sufficient to configure all Kong instances, and replacing a controller replica does not take long (although I haven't tested to confirm, offhand I wouldn't expect starting a new controller replica to take much longer than leader takeover).

Note that configuration is not valid forever: the configuration available to a Kong instance will eventually go out of date, particularly upstream application endpoints (an outage that takes out a bunch of applications and the controller both will result in a bunch of new and deleted endpoints in short order, and you'll want Kong to route to new endpoints and not try routing to old). You should not rely on existing configuration as a high availability mechanism alone: it is a stopgap measure to allow some degree of service while slower high availability mechanisms kick in.

## Testing

Distributed systems are complex and rapidly supersede human ability to predict their exact behavior in failure scenarios. You cannot plan a perfect high availability system by thinking about possible failure domains and resilience mechanisms. An untested high availability system is not a high availability system, it is a prayer.

While running through intentionally-created outages is not guaranteed to confirm every possible scenario has been handled, it will demonstrate that your systems are indeed resilient to some classes of failure and surface cases where resilience mechanisms are not achieving the desired effect.

You should therefore lay out general failure scenarios you need to resist and then simulate them as best possible. If you design for resilience against a region going offline, simulate this (for example, by adding temporary firewall rules to that region to discard all external traffic) and monitor how failure compensation systems in other regions perform and whether application availability is affected for the still-online regions and external clients.

**Comment by lahabana** [comment]
There's not demand for this. Let's close and we'll reopen if it's asked.
