### ISSUE TITLE
KIC not setting gateway address when using ingress instead of service type loadbalancer

### ISSUE THREAD

**Issue by rtavares-loft** [Kong/kubernetes-ingress-controller#5407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I deploy my Kong Ingress Controller exposing my proxy service using an Ingress resource instead of a Service of type LoadBalancer, the Gateway resource address status is not filled with the value provided with the env `CONTROLLER_PUBLISH_STATUS_ADDRESS`
- Services:
![Screenshot 2024-01-05 at 4 00 14 PM](https://github.com/Kong/kubernetes-ingress-controller/assets/113139953/c9ef3591-6ce2-4ceb-ad33-66a8eb2a8d02)
- Ingress:
![Screenshot 2024-01-05 at 4 00 30 PM](https://github.com/Kong/kubernetes-ingress-controller/assets/113139953/b9d2b4af-6c82-4b41-b777-10ea83812a05)
- GatewayClass:
![Screenshot 2024-01-05 at 4 00 42 PM](https://github.com/Kong/kubernetes-ingress-controller/assets/113139953/9de39de1-80cc-4c24-a424-3d6084bd66f8)
- Gateway:
![Screenshot 2024-01-05 at 4 00 50 PM](https://github.com/Kong/kubernetes-ingress-controller/assets/113139953/8a1f6721-5d97-4138-b04a-58ffb5505308)
- Controller deployment:
![Screenshot 2024-01-05 at 4 13 28 PM](https://github.com/Kong/kubernetes-ingress-controller/assets/113139953/17be4678-7d69-4088-a2b8-be4ea5c3b416)

### Expected Behavior

The `status.address` of the Gateway object should be equal to the value in the `CONTROLLER_PUBLISH_STATUS_ADDRESS` env var of the ingress controller pod.

### Steps To Reproduce

```markdown
1. Install the Gateway API CRDs using: kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml
2. Create the gateway class and gateway using:

echo "
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kong
  annotations:
    konghq.com/gatewayclass-unmanaged: 'true'

spec:
  controllerName: konghq.com/kic-gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kong
spec:
  gatewayClassName: kong
  listeners:
  - name: proxy
    port: 80
    protocol: HTTP
" | kubectl apply -f -

3. Install KIC using the helm chart (kong/ingress) with values:

controller:
  ingressController:
    env: 
       publish_status_address: k8s-ingressk-***********.amazonaws.com
gateway:
  proxy:
    type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: alb
      pathType: Prefix

4. Verify the `status.address` of the gateway as empty
```

### Kong Ingress Controller version

```shell
v3.0
```

### Kubernetes version

```shell
"clientVersion": {
    "major": "1",
    "minor": "29",
    "gitVersion": "v1.29.0",
    "gitCommit": "3f7a50f38688eb332e2a1b013678c6435d539ae6",
    "gitTreeState": "clean",
    "buildDate": "2023-12-13T08:45:02Z",
    "goVersion": "go1.21.5",
    "compiler": "gc",
    "platform": "darwin/amd64"
  },
"serverVersion": {
    "major": "1",
    "minor": "28+",
    "gitVersion": "v1.28.4-eks-8cb36c9",
    "gitCommit": "b4ddd686b005f445825bd0afd5dba24d4414d4cf",
    "gitTreeState": "clean",
    "buildDate": "2023-11-22T21:52:14Z",
    "goVersion": "go1.20.11",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
```

### Acceptance criteria

- [ ] `--publish-status-address` (or env: `CONTROLLER_PUBLISH_STATUS_ADDRESS) has an effect on `Gateway` resource similarly as it does for `Ingress`.

**Comment by backjo** [comment]
I just noticed this on our deployment as well - i think what would make sense from our PoV is specifying something along the lines of CONTROLLER_PUBLISH_INGRESS which would basically propagate the status information from the Ingress powering the Kong proxy to ingresses managed by the controller

**Comment by pmalek** [comment]
`Gateway` resource currently only supports the `--publish-service` flag (or the corresponding `CONTROLLER_PUBLISH_SERVICE` env variable).

https://github.com/Kong/kubernetes-ingress-controller/blob/f154d10100b81a96572f1ffd2266660bf6598b5f/internal/controllers/gateway/gateway_controller.go#L597-L610

The `--publish-status-address` flag does not have an effect for `Gateway` resources.

We can add that as part of this issue though.

**Comment by rainest** [comment]
Naturally this ended up being more complicated than I thought because our unmanaged mode continues to be kinda hard to square with the spec.

It does make to honor the override flags for the unmanaged Gateway mode currently in the controller. The same use case where there's some hop in front of the proxy Service still applies, and we trust that users can provide whatever value is appropriate for their network there.

Currently, unmanaged mode copies the publish/proxy Service addresses into both the Gateway spec addresses and status addresses. Review of the addresses sections of https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.Gateway and https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.GatewayStatus indicates that we shouldn't actually do this for the spec addresses. Spec addresses are user requests, and you can't meaningfully request anything via the Gateway spec in unmanaged mode--we always use whatever's actually in place for the proxy Deployment and Services.

For some configuration we further set conditions if Gateway configuration doesn't match the unmanaged resources, but it doesn't seem this would be useful here. Although there is a `GatewayReasonAddressNotUsable` reason for `GatewayConditionProgrammed=false` when implementations cannot assign requested addresses, unmanaged can't ever assign requested addresses, so all we'd be able to confirm is whether you've successfully copied the current set of proxy service addresses into the Gateway, which is somewhat pointless. Realistically you should just leave that part of the spec blank.

There is a fair bit of wiggle room to assign "dynamic" addresses that don't match the spec set in my reading, so I think populating status with either the publish service or override addresses is reasonable for unmanaged mode. Meaningful conformance here basically requires operator provisioning.
