### ISSUE TITLE
`GRPCRoute` conformance

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#5705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Gateway API v1.1 will be released soon with a new set of GRPC conformance tests, and the [graduation](https://github.com/kubernetes-sigs/gateway-api/milestone/18) of the `GRPCRoute` API. Since we are implementing the `GRPCRoute`, we want to run the new `GRPCRoute` tests and claim conformance with it.

### Acceptance Criteria

- [ ] The `GRPCRoute` conformance tests are successfully run.
- [ ] The default behavior changes only affect feature-gated alpha capability
- [ ] Documentation explicitly covers both GRPC and GRPCS backend cases.

**Comment by tao12345666333** [comment]
Let me pick up this one.

**Comment by tao12345666333** [comment]
Update:

We encountered errors in some conformance test cases. 

This happens because when the KIC translator processes the GRPCRoute resource, it sets the default protocol to `grpcs` instead of `grpc`. https://github.com/Kong/kubernetes-ingress-controller/blob/57019123e5c822903fbfbe768b025de1252801c7/internal/dataplane/translator/translate_grpcroute.go#L56-L59

More background context here:
* #4273
* https://github.com/Kong/kubernetes-ingress-controller/pull/5283


When we implemented this feature, the Kong Gateway version used was 3.5, which is [based on OpenResty 1.21.4.2](https://github.com/Kong/kong/blob/5c1606953c846f58c8441803ef76b63f384b5af6/.requirements#L3). Since version 3.6, it is based on [1.25.3.1](https://github.com/Kong/kong/blob/de77c2941fcc778bd992de4e8bb46515e2b8709c/.requirements#L3) which added support for "[Allow h2c and HTTP/1.1 support on the same listening socket](https://trac.nginx.org/nginx/ticket/816)"

We have set this default value grpcs in KIC#5283 because we don't want to break users existing configurations.

- **However, support for GRPCRoute is configured through `GatewayAlpha` and is not enabled by default.**
- As Gateway API's GRPCRoute is about to become generally available, I think we should consider modifying this behavior. We will implement the GRPCRoute v1 API, and it will be enabled like other GWAPI resources.

**Why we need to change the default GRPCRoute's protocol** 

- pass the GWAPI's conformance test
- I have checked other GWAPI implementations. All of them's default implementation is `grpc` instead of `grpcs`.

**Comment by mflendrich** [comment]
Decision reached with @tao12345666333 :
- Since the GRPCRoute implementation is alpha and feature-gated, we will change the default behavior in a minor version of KIC
- The changelog entry will explain how to migrate given the new default
- The documentation will explicitly cover both the "GRPC non-TLS backend" and the "GRPCS" cases.

**Comment by shaneutt** [comment]
I'm unavailable and wont be able to dig in for the next few days. I did however share this thread with other Gateway API folks and we're agreed to hold on releasing `v1.1` until we've got things sorted out. @mlavacca: if you're working on this the next couple days and have any updates, let Rob and Richard know any updates (on Kubernetes slack) as they're aware of the situation.

**Comment by tao12345666333** [comment]
The reason why the conformance test fails is because the test case only uses plaintext, but since KIC sets the protocol to grpcs, it will fail.

I have tested that it works correctly if set to grpc.

Thanks @rainest and @shaneutt. I will reach out to the GWAPI team.

**Comment by tao12345666333** [comment]
Interim conclusion:

* GWAPI will bring test cases for `grpcs`, and the current test case is clearly defined as h2c protocol through `app-protocol`. Therefore, KIC also needs to support the h2c protocol.

I will complete this goal through the following steps to avoid generating a huge PR and facilitate review.

- [ ] Upgrade the GWAPI version to the commit before GRPCRoute GA, so that KIC can better complete the adaptation of GWAPI.  For example, experimental conformance testing has become a standard. https://github.com/Kong/kubernetes-ingress-controller/pull/5863
- [ ] Make KIC support h2c protocol to pass the conformance test
- [ ]  Introduce GRPCRoute v1 support
- [ ] Once the GWAPI publishes a new release, upgrade to the latest version.

**Comment by tao12345666333** [comment]
since #5776 hasn't been merged, I will reopen this issue.

**Comment by tao12345666333** [comment]
the docs PR https://github.com/Kong/docs.konghq.com/pull/7501 has been merged. I think we can close this one.
