### ISSUE TITLE
EKS k8s with NLB has TargetGroup unhealty

### ISSUE THREAD

**Issue by whatz-admin** [Kong/kubernetes-ingress-controller#596]
### Summary

Kong deployed via `kubectl apply -f https://bit.ly/k4k8s` doesn't work.

**Kong Ingress controller version**
0.8.0

### Kubernetes version

`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
`
### Environment

- AWS:
- Amazon's EKS k8s 1.15 AMI
- kubectl apply -f https://bit.ly/k4k8s

### Problem

I'm trying do deploy Kong via Kustomize or static yaml. It seems that they both use the AWS Network Load Balancer. For some reason, the target groups are in an unhealthy state. I have no problem running Kong installed via Helm. The difference is that Helm chat is using a classic load balancer there for all works. 
  
Kong controller created by `kubectl apply -f https://bit.ly/k4k8s` doesn't work. 
Kong installed via : `helm install kong/kong --generate-name --set ingressController.installCRDs=false`  works.

### Steps To Reproduce

1. On Amazon EKS cluster just launch `kubectl apply -f https://bit.ly/k4k8s`

**Comment by magneland** [comment]
We have run into the same issue :-(

**Comment by rainest** [comment]
What healthcheck was configured, and what error condition does it indicate? https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html#check-target-health

Are the cluster subnets properly tagged for load balancer use? https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html#subnet-tagging-for-load-balancers indicates that this is done automatically now, but that change is fairly recent.

Are security groups/network ACLs (https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-troubleshooting.html#target-not-in-service) set to allow communication between the load balancer and pods?

**Comment by magneland** [comment]
```---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: kong-proxy
  namespace: kong
spec:
  externalTrafficPolicy: Cluster```

**Comment by hbagdi** [comment]
Awesome. We have a ticket tracking to change the default to externalTrafficPolicy to `Cluster`. Buggy EKS implementation has caused more problems with the `Local` policy than it is worth. 
Thank you for your patience.

**Comment by namanrawal47** [comment]
I'd like to reopen this issue because the latest updates to https://bit.ly/k4k8s have created further problems. I have a 3-node cluster with an NLB provisioned to the kong-proxy service. In the latest update, Kong does not include an externalTrafficPolicy field, and so after I unsuccessfully deployed the latest manifest, I added back externalTrafficPolicy: Cluster because doing so had previously solved my issue. However, I have no idea what the issue could be this time around. 

**Kong Ingress Controller Version: kong/kubernetes-ingress-controller:1.3**
**Kubernetes Version**: Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
**Environment**: AWS GovCloud, AMI 1.20.4-20210826

**Additional Details:**
- platform version: eks.2
- ingress controller logs: time="2021-09-08T18:28:46Z" level=info msg="no configuration change, skipping sync to kong" component=controller
- ingress controller proxy logs: 2021/09/08 18:18:39 [notice] 22#0: *6 [lua] init.lua:260: purge(): [DB cache] purging (local) cache, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "127.0.0.1:8444"
127.0.0.1 - - [08/Sep/2021:18:18:40 +0000] "POST /config?check_hash=1 HTTP/1.1" 201 6108 "-" "Go-http-client/1.1"

**Comment by rainest** [comment]
Per comment edit:

> It seems that the problem was my organization's network security policies that were restricting me from executing the actions "authorizesecurityingress" and "createsecuritygroup". After those permissions were added, I was no longer getting any 403 errors in the kong-proxy logs. This can be closed.

re-closing.
