### ISSUE TITLE
Namespace restriction on usage of a KongClusterPlugin in certain namespaces

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#684]
Restrict usage of certain KongClusterPlugin resource in certain namespaces.

**Comment by hbagdi** [comment]
Some context in this slack thread: https://kubernetes.slack.com/archives/CDCA87FRD/p1585659815039000

**Comment by mflendrich** [comment]
What is the specific problem we're trying to solve here? It's not immediately clear to me from the Slack discussion attached.

**Comment by seh** [comment]
I just went back and read the entire thread again. The problem remains, expressed as questions:
- _How does a cluster operator mandate that some plugins be used on namespaced objects like Service and Ingress?_  
  Perhaps all of them must use some sort authentication or auditing.
- _How does a cluster operator prevent use of some plugins with namespaced objects?_  
  Perhaps sending traces to a SaaS provider will leak sensitive data.
- _How does a cluster operator define configuration that can be shared across namespaces, but not apply that configuration to all namespaced objects?_  
  Perhaps we'd like to configure the Zipkin plugin once, but use it in many _Services_, but not all of them.

A cluster operator can control via RBAC who can edit Kong-specific objects like _KongPlugin_ and _KongConfiguration_, but she can't so easily prevent namespace-level authors from editing the annotations on their _Service_ and _Ingress_ objects. We would need an admission control plugin like Gatekeeper or Kyverno to get down to that level of granularity.

**Comment by shaneutt** [comment]
@seh from your last comment it wasn't entirely clear to me whether your team has a continued need for this, can you help me to better understand your needs in this regard?

**Comment by seh** [comment]
We haven't been struggling with the security concerns. I maintain my original stance about how this _should_ work, but I can't claim that we're suffering that lack today.

We _do_ continue to struggle with how Kong configuration is bound to _Ingress_ and _Service_ objects, beyond controlling who can manipulate that configuration. I'd prefer that the Kong-related configuration sit separate from those objects, and refer to them, kind of like _RoleBinding_ sits between principals like _ServiceAccount_ and _Role_ or _ClusterRole_ objects. We wind up trying to patch annotations on our _Ingress_ objects, cramming lists or sets into CSV, and so on. It's hard to figure out which Kong-related configuration impinges on the _Ingress_.

**Comment by shaneutt** [comment]
Thanks for the update. So as far as this issue is concerned it sounds like there's no immediate need.

On the other hand, if I'm understanding your second point correctly the concept of having separate objects which refer to the core objects like bindings to add Kong-related configuration may fit in well with some of the work we're doing to implement [Gateway APIs](https://gateway-api.sigs.k8s.io). In Gateway APIs implementation-specific options (in our case then, Kong Gateway options) for any route object like `HTTPRoute` (which is in many ways meant to be the successor to `Ingress` if you're not familiar) are done via [Policy objects](https://gateway-api.sigs.k8s.io/v1alpha2/references/policy-attachment/) which are implementation-specific CRDs that follow some specification guidelines and ultimately get "bound" to routes. Is this resonating with the problem you were trying to convey above, or am I way off?

**Comment by seh** [comment]
> Is this resonating with the problem you were trying to convey above, or am I way off?

I think you've understood my goal. The Gateway API's approach sounds much like what I was describing. It's interesting to see how while they can't lock down exactly which _CRDs_ will be involved and what they'll contain, they're mandating certain conventions (with the "spec.default" and "spec.override" fields) that should apply to all of them that wish to play along.

**Comment by shaneutt** [comment]
> I think you've understood my goal. The Gateway API's approach sounds much like what I was describing. It's interesting to see how while they can't lock down exactly which _CRDs_ will be involved and what they'll contain, they're mandating certain conventions (with the "spec.default" and "spec.override" fields) that should apply to all of them that wish to play along.

Sounds good. How would you like to proceed from here?
