### ISSUE TITLE
Add support for (all) CRDs in Gateway API

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#692]
This is an umbrella issue to track all the work that needs to be done to support CRDs being worked in the gateway-api sub-project of SIG-Network:

https://github.com/kubernetes-sigs/gateway-api

**Comment by hbagdi** [comment]
This is currently blocked on #686

**Comment by shaneutt** [comment]
We're going to provide an initial implementation of Gateway APIs using the recently released [v0.2.x specification](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.2.0).

Recent work which [attempted to add single controller multi proxy support in DBLESS mode](https://github.com/Kong/kubernetes-ingress-controller/issues/702) sparked @Kong/team-k8s to do a spike for a [new architectural direction for the Kubernetes Ingress Controller (KIC)](https://github.com/Kong/kubernetes-ingress-controller/issues/1035), dubbed ["Railgun"](https://github.com/Kong/kubernetes-ingress-controller/tree/8003212b99c0975baf5a6251ddf6d8a8b5ac3951/railgun).

The first Gateway API implementation will be done against the railgun KIC architecture and @Kong/team-k8s will be grooming this issue for further priority in the coming weeks.

**Comment by shaneutt** [comment]
With several KIC 2.0 releases done (and since that work is a pre-requisite for our Gateway API work) I wanted to do a status update:

After [KIC 2.0 Beta](https://github.com/Kong/kubernetes-ingress-controller/milestone/12) is launched we will be putting effort into an initial implementation of Gateway APIs. The new target given recent updates will be to support [v0.3.0](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.3.0) however, rather than `v0.2.0`.

**Comment by hbagdi** [comment]
@shaneutt This issue is linked from https://gateway-api.sigs.k8s.io/implementations/. Either re-open this issue or update the implementations page. I recommend the former.

**Comment by shaneutt** [comment]
At this point this issue is being closed as we're no longer using it for tracking Gateway API support and the link to it from the Gateway API implementations page has been removed in favor of the [now present preview documentation in docs.konghq.com](https://docs.konghq.com/kubernetes-ingress-controller/2.2.x/guides/using-gateway-api/).

Tracking (and contributing) planning and design for Gateway API support in KIC can be done via the [Gateway API KEP](https://github.com/Kong/kubernetes-ingress-controller/blob/main/keps/0002-kong-gateway-api.md).

Tracking (and contributing) development for `HTTPRoute`, `TCPRoute`, `UDPRoute`, and `TLSRoute` has moved to our [Gateway API Milestone #2](https://github.com/Kong/kubernetes-ingress-controller/milestone/22) and the individual issues therein.

Tracking support level and maturity for Gateway API can be done using the [Feature Gates Documentation](https://github.com/Kong/kubernetes-ingress-controller/blob/main/FEATURE_GATES.md).

Also watch our [blog posts](https://konghq.com/blog/) for upcoming news about Gateway API support, which we kicked off with the [2.2 Release post which introduced Gateway API support as a technical preview in KIC](https://konghq.com/blog/kong-ingress-controller-2-2/).
