### ISSUE TITLE
Setup e2e tests

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#694]
Currently, the tests written in the controller codebase test the controller itself but we do not perform a full integration of the controller with a k8s setup and Kong running with it.
Setup a simple and maintainable test setup to run automated e2e test.

**Comment by StarpTech** [comment]
This is a very important issue because I think it's the major reason why knative integration is currently broken.

- https://github.com/Kong/kubernetes-ingress-controller/issues/740
- https://github.com/Kong/kubernetes-ingress-controller/issues/742

This also prevents me from using the controller in production.
