### ISSUE TITLE
duplicate key-auth credentials cause the ingress controller to fail syncing all future configuration

### ISSUE THREAD

**Issue by agringeri** [Kong/kubernetes-ingress-controller#729]
### Summary

If a KongConsumer references two secrets (they could be different secrets) that contain the same key, then the ingress controller cannot successfully sync any future configuration to Kong.

**Kong Ingress controller version**

0.9.1

**Kong or Kong Enterprise version**

2.0.4

### Kubernetes version

`Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T15:58:45Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}`

### Environment

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): alpine
- **Install tools**: helm
- **Deployment**: DB (postgres)

### What happened

Two secrets with the same key were listed as configuration for a KongConsumer. The ingress controller fails to sync any future configuration until the duplicate key is removed. 

### Expected behavior

The ingress controller should skip duplicate keys or fail safely and allow other unrelated configuration to sync.

### Steps To Reproduce

1. Reference two secrets with the same key in a KongConsumer, or reference the same secret in different KongConsumers.
2. `E0610 20:02:43.392469 1 controller.go:128] unexpected failure updating Kong configuration: inserting key-auth into state: entity already exists`

**Comment by rainest** [comment]
This is a known limitation in the current controller sync loop. Addressing it effectively (gracefully ignoring configuration the controller cannot apply and updating status information on related resources) is on our long term roadmap.

For now, the most effective way to deal with conflicting configuration is to use the [admission controller](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/deployment/admission-webhook.md). The admission controller will reject invalid configuration at the Kubernetes level, i.e. kubectl will fail to apply it and inform you of the conflict. Because the invalid configuration is never persisted in etcd, the controller won't attempt to create it and block the sync loop when it fails.

**Comment by agringeri** [comment]
This specific case doesn't appear to be covered by the admission webhook. I started with a fresh install of Kong with no configuration, added two secrets of type `key-auth` and with the same key, and listed those keys under a KongConsumer and applied them. The webhook did not appear to have an issue with it: 

```
kubectl create secret generic kong-test-key-1 --from-literal=kongCredType=key-auth --from-literal=key=abcd
```
```
kubectl create secret generic kong-test-key-2 --from-literal=kongCredType=key-auth --from-literal=key=abcd
```
```
echo "apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: test-consumer-1
username: test-consumer-1
credentials:
- kong-test-key-1
- kong-test-key-2" | kubectl apply -f -

> kongconsumer.configuration.konghq.com/test-consumer-1 configured
```

However, the ingress-controller gets hung up and refuses to sync any configuration until the problematic consumer is removed:
```
E0622 21:05:00.129217       1 controller.go:128] unexpected failure updating Kong configuration: 
inserting key-auth into state: entity already exists
```

**Comment by rainest** [comment]
Odd--it should, since the webhook is basically "perform basic checks, then check the proposed resource against the Kong admin API" and should, as such, be able to reject anything that the admin API will actually reject.

However, IIRC the API endpoint used for this was originally designed to run schema checks; it's quite possible that doesn't do conflict checks. Will have to check on that further in test instances and maybe file a feature request to the Kong core team.

**Comment by hbagdi** [comment]
> it's quite possible that doesn't do conflict checks.

It doesn't. 

The immediate fix should be to not make the admission controller more accurate but make the controller more resilient to such configuration issues (ignore the new secret with the same api-key).

**Comment by mflendrich** [comment]
Blocked by #1035. After migration to kubebuilder, the proposed solution is to identify conflicting resources (secrets, consumers) in an input controller, and refuse to reconcile them with a visible error posted via `status`.

**Comment by shaneutt** [comment]
I'm taking this to write a patch for it in `v2` that will tolerate the duplicate, but ignore it and throw an error in the logs to avoid the persistent failure state.

**Comment by shaneutt** [comment]
After further considerations in https://github.com/Kong/kubernetes-ingress-controller/issues/1722 we've decided that the solution in https://github.com/Kong/kubernetes-ingress-controller/pull/1716 ultimately needs to be reworked into the admission webhook. We avoided the admission controller in the first attempt because the component is technically optional and therefore we would expect some tribulations with constraint violations to continue, but after careful consideration we're going to take the validation logic that was added in #1716 and re-apply it in the admission webhook.

This is being re-opened with new acceptance criteria:
- [ ] the admission webhook uses the new validation code under `internal/adminapi/validation` to validate against `KongConsumer` credentials constraint violations
- [ ] the documentation reflects that this problem will be present when the admission webhook is not deployed
- [ ] the CHANGELOG.md us updated to note these changes

**Comment by shaneutt** [comment]
The fix provided in https://github.com/Kong/kubernetes-ingress-controller/pull/2015 specifically adds this validation to the validating webhook. This was added to the 2.x series and we can expect this to land in an upcoming minor or patch release of v2.
