### ISSUE TITLE
do not treat kong as a special class

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#731]
The current behavior treats “kong” as a special ingress.class: if controller is configured with ingress class as “kong”, it will also satisfy all ingress resources which don’t have an Ingress class defined. If an ingress class is not specified in the controller and an ingress resource has “kong” as its ingress class, then the controller takes control of the resource.

The scope of the work:
- remove the special treatment
- set the class to `kong` be default.
- this should be an effect automatically based on the above two changes, but if not, then: controller should ignore all ingress v1beta1 resources which do not have an ingress.class annotation set to "kong".

For more details see the doc in #690.

**Comment by rainest** [comment]
AFAIK implementing #732 does this. `kong` is already the default per https://github.com/Kong/kubernetes-ingress-controller/blob/0.9.1/internal/ingress/annotations/annotations.go#L49 (which is then used in flags.go), and I don't think we have special treatment other than allowing classless ingresses when `kong` was the controller class.

With the addition of fb3ab86 to #767 that's the case.

To try and check this, I changed instances of `kong` in https://github.com/Kong/kubernetes-ingress-controller/blob/fc5de5c9f2fe530e67c55cec8023a882d4de9208/internal/ingress/annotations/annotations_test.go#L35-L44 to some other string, and didn't see any change in test results. We can stick a few extra non-`kong` expected success cases in there if we like.

**Comment by rainest** [comment]
ListKnativeIngresses is one exception because it uses a [special validKnativeIngressClass function](https://github.com/Kong/kubernetes-ingress-controller/blob/0.9.0/internal/ingress/store/store.go#L173-L180) that hard-codes lazy/allow empty matching if using _the default_ class, which I think does violate the spirit of #731 if not the letter (who cares if we change the default class and it's special behavior for for "mycoolnewdefault" instead of "kong"?), so that probably needs to change.

Do we care if that's controlled with a flag and/or preserves the default behavior (always allow empty if using the default class)? I'd like to use annotations validity function and the value of the Ingress matching flag, i.e. if you set `--process-classless-ingress-v1beta1` it applies to both Ingress and KNative "ingresses", but I think that breaks down because the flags are versioned, and ingresses.networking.internal.knative.dev doesn't track Ingress.

**Comment by rainest** [comment]
Closing per #815 and #767
