### ISSUE TITLE
Upstream IP's not updated

### ISSUE THREAD

**Issue by phlegx** [Kong/kubernetes-ingress-controller#773]
### Summary

For some reasons Kong Ingress controller has stopped updating the upstream IP's when we for example deploy with `kubectl patch`. For new pods it doesn't even create the upstream it seems.

**Kong Ingress controller version**
`0.9.0`

**Kong or Kong Enterprise version**
`2.5.0`

### Kubernetes version

` v1.17.5`

### Environment

- **Cloud provider or hardware configuration**: Bare Metal with Rancher (v2.4.5)
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04
- **Kernel** (e.g. `uname -a`): inux pre-production1 5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: Helm 3.x

### What happened
Upstreams and upstream IP's are not created

### Expected behavior
Upstream and upstream IP's should be created trough Kong Ingress

### Steps To Reproduce

Apply `kubectl patch` with a newer docker image to an existing pod

**Comment by tak1n** [comment]
Just a short heads up, I'm a co worker of @phlegx and we tried to further look into the problem (I'm not that experienced with kubernetes and kong-ingress-controller yet, so forgive me if I miss something obvious).

On deployment (CI) we execute following kubectl command:
```
11:18:11  + kubectl --kubeconfig /root/.kube/config_pre-production patch deployment --namespace bms bms-api --patch spec:
11:18:11   template:
11:18:11    spec:
11:18:11     containers:
11:18:11     - name: bms-api
11:18:11       image: registry.onlim.com/pre-production/bms/bms:v5.7.0-150-g65374d01d-284-release-5.8.0
11:18:12  deployment.apps/bms-api patched
```

We tried a few things to further hunt down the problem:

- Scaling down Kong to 1 instance
- Scaling down the services being deployed to 1 instance
- Setting `--v` flag mentioned at https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/troubleshooting.md#debug

After the last point it seemed to be fixed (also removed the flag again and upscaled kong and related services) so seemingly recreating kong with its ingress-controller container fixed the situation for us. Unfortunately we can't provide further details on the specific problem we had.

**Comment by hbagdi** [comment]
Can you share the logs of Kong and Kong Ingress Controller from around the time when this issue happened?

**Comment by phlegx** [comment]
We did check the logs with verbose, but couldn't find any suspicious output there. Unfortunately we don't have the log output anymore. 

Lets close this issue for now. When it happens again, we will open it and provide you with the logs.

thanks!

**Comment by tak1n** [comment]
We faced the same issue yesterday while deploying to production. Here are the kong ingress logs (without verbose flag) from our 4 kong instances https://gist.github.com/tak1n/e31e81d30dd2092baccf2e6716a915fa.

Note that the 4th kong instance crashed as docker on this specific server had some issues.
The deployment was started ~ 20:11

**Comment by tak1n** [comment]
We keep facing this issue on a regular basis, today I was able to catch the logs while having kong ingress controller unning in verbose mode with `--v=3`.

Here are the logs https://gist.github.com/tak1n/11fcf6d5a90a5e4991c44f7e8244d361.

From what I can observe the Events are getting triggered properly, also the logs contain all the new IP's of the 3 new pods (as well as the old 3 one). What is weird from the pods in question is that they receive 1 or 2 request at the beginning (on fresh deployment) and then it stops (this would indicate that kong for a short point in time has the proper IPs assigned as upstreams?)

Here the log from one pod https://gist.github.com/tak1n/4e2af77c66c21c8a0f4281824f123796. Note the request at around 20:45 (which was when we deployed) and the next one after I fixed the IPs manually through Konga.

**Comment by rolandg** [comment]
The error disappeared at least for now. We are not entirely sure what helped but either it was the deletion & recreation of kong or the `unique constraint violation","fields":{"name":"example.com"}` errors I fixed with deleting the SNI manually and let the ingress-controller recreate it.

**Comment by Bryji** [comment]
We've encountered something that looks like this issue twice recently. It manifests as 499 responses sent by Kong to client requests. Closer investigation shows upstream service IPs not having been updated (e.g. after pods on a spot instance get terminated). We also noted a cessation of logs from the Ingress Controller, although it does seem to pass health checks. Killing the pod elected leader as Ingress Controller has worked around the issue when we've seen it. We have configured the increased logging (''-v=3"), will check back with logs when we encounter it again.

**Comment by rolandg** [comment]
This issue happened less often now but didn't disappear entirely.
We are suspecting the kube-api / etcd to be the problem here.

How is this working internally? 
I guess you are using watches on the kube-api.
Is it possible that a timeout here causes that problems?
Would the ingress-controller automatically reconnect if this connection is interrupted?

**Comment by jconners-aspect** [comment]
I experienced the same problem where the IPs associated with the upstream targets/endpoints were not updated. I noticed the following log messages from the ingress controller after the last successful handling of a request for the upstream service and before the first failed handling of a request for the upstream service.

I1009 12:00:14.211803       1 parser.go:1947] endpoints found: [{100.116.225.29 8080}]
E1009 12:00:14.744029       1 controller.go:128] unexpected failure updating Kong configuration: 
loading configuration from kong: targets: 500 Internal Server Error {"message":"An unexpected error occurred"}
W1009 12:00:14.744051       1 queue.go:112] requeuing bench/janusapi, err loading configuration from kong: targets: 500 Internal Server Error {"message":"An unexpected error occurred"}

Not sure if the log messages above have anything to do with the problem of stale IPs for the upstream service.
Since the upstream IPs were stale, the upstream service couldn’t be reached, so the request failed resulting in a 499 response back to the client.
Killing the pod associated with the ingress controller leader resolved the issue.
The Kong app version is 2.0.4, and the ingress controller app version is 0.9.1.

**Comment by mflendrich** [comment]
@phlegx @tak1n, is the problem still prevalent?

**Comment by jconners-aspect** [comment]
@mflendrich This problem did occur 1 or 2 more times after last updating this issue. I haven't seen it happen in several months though. However, we haven't made any changes to remedy the issue either.

**Comment by l4nd0r** [comment]
@mflendrich We are still having problems with this in our test environments. 
We tried a couple of things like activating the admission controller but nothing helped.
Currently we are restarting kong or redeploying the service when updating upstream ips fails.

**Comment by phlegx** [comment]
@mflendrich I'm working together with @l4nd0r and  @tak1n so as @l4nd0r already said, unfortunately it still happens to us sometimes.

**Comment by cpcostaneves** [comment]
@l4nd0r , @phlegx We were having frequent issues with upstream target IPs not being updated, forcing us to restart kong. In our case it was targets with weight=0 in postgres, created by kong 2.1. The way kong deletes target was changed on kong 2.2 and migration job left some old targets with weight=0 . See my comment on https://github.com/Kong/kubernetes-ingress-controller/issues/1025#issuecomment-803002692

Don't know if it is same thing here, but just to add some info.

**Comment by l4nd0r** [comment]
@cpcostaneves Thanks :) 
I checked our dbs and we had to delete a couple of weight=0 targets in every database.
We'll see if that solves the issue.

**Comment by syedrakib** [comment]
We are facing issue on this. Our kong APIs point to a remote domain which is backed by a CDN. And CDN's, by right, can change their IP address anytime without notice. And every time that happens, our kong API fails because kong continues to forward traffic to the previous IP of the CDN. We have to restart the kong pods to sort of refresh the DNS IP every time this happens.

**Comment by rainest** [comment]
Anyone affected, do you still see this in KIC 2.1?

We discovered a deck bug where it silently exited successfully if its context expired, even if it had not synced all objects. This was fixed in https://github.com/Kong/kubernetes-ingress-controller/issues/2031 and incorporated into KIC in https://github.com/Kong/kubernetes-ingress-controller/commit/a0f6eb48eed2f8f1d0b992adee61da70be902721

Note that the fix will only properly error out when this occurs: if you do see (new) errors on 2.1, you need to set `–proxy-timeout-seconds` to a higher value.

@syedrakib this issue only applies to the Endpoints of Kubernetes Services running in the cluster. External hostnames aren't updated at all: KIC places the external hostname as-is in the proxy configuration and allows DNS to provide the current IPs for that hostname, which expire based on the record's TTL. You'll want to check with your CDN provider--under normal circumstances they shouldn't be taking IPs out of service until they've updated records and allowed TTL to expire.

**Comment by ChongmingDu** [comment]
KIC 2.2 reappear

**Comment by shaneutt** [comment]
> KIC 2.2 reappear

Hi @ChongmingDu thanks for reporting. As per Travis' comment above:

- https://github.com/Kong/kubernetes-ingress-controller/issues/773#issuecomment-1023739202

Is it the case that when you get the issue you now see a clear error about the issue? And if so, does increasing the `--proxy-timeout-seconds` work as was suggested?

**Comment by ksgnextuple** [comment]
Hi we are facing this issue in **KIC 2.5** and **Kong 2.8** on **k8s 1.24.6**.  Another thing we observed is the new pod IP does not get updated at all and the old target remains in the postgres DB, with weight as 100. We had to scale down the deployment, delete the data in postgres and restart the deployment. Noticed this for the past few days. This happens in **newly deployed applications** with new ingress resources only.
