### ISSUE TITLE
Undesired trailing slash added to upstream_uri

### ISSUE THREAD

**Issue by vrobinho** [Kong/kubernetes-ingress-controller#819]
### Summary

A trailing slash is automatically added to the path of the upstream_uri while it's not defined in the service path. As the path known on the destination does not contain any trailing slash, we get a 404.

Is there a way to prevent the trailing slash to be automatically added?

**Kong Ingress controller version**

0.9.0

**Kong version**

2.0.2

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"5737fe2e0b8e92698351a853b0d07f9c39b96736", GitTreeState:"clean", BuildDate:"2020-06-24T19:54:11Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

AKS + Installation via Helm

### What happened

A trailing slash is automatically added to the path of the upstream_uri while it's not defined in the service path. As the path known on the destination does not contain any trailing slash, we get a 404.

Is there a way to prevent the trailing slash to be automatically added?

### Expected behavior

No trailing slash is added to the upstream_uri

### Steps To Reproduce

1. Install a pod exposing an endpoint at a specific path without trailing slash, by example '/foo'.
2. Create a service and ingress. The ingress path is different from the endpoint path, by example '/kung'
3. Create a kongIngress such that the strip_path property of the route section is set is true and with the path property of the proxy set to '/foo'.
4. Link the the kongIngress with the service and the ingress

### Additional details & logs 

Here is the output of the file-log plugin:
```
{
   ...
   "service" : {
      ...
      "path" : "/foo",
      ...
   },
   "response" : {
      ...
      "status" : 404,
      "headers" : {
         ...
      }
   },
   "upstream_uri" : "/foo/",
   ...
}
```

In another environment where we are still using kong 1.4.2 and the kong-ingress-controller 0.7.0 we do not have the problem. Here is the output of the file-log plugin in that other environment:

```
{
   "service" : {
      ...
      "path" : "/foo",
      ...
   },
   ...
   "upstream_uri" : "/foo",
   ...
}
```

**Comment by rainest** [comment]
@vrobinho Could you share the Ingress/Service YAMLs you have, along with the corresponding Kong route+service you see after via the admin API?

We're perhaps not on quite the same Kong/controller versions, but with a `strip-path: true` Ingress and a `path: /anything` annotation on the Service I get the following:

```
{"id":"461c7c41-bec0-403b-981c-686dbdc73f6b","path_handling":"v0","paths":["/space"],"destinations":null,"headers":null,"protocols":["http","https"],"created_at":1600299352,"snis":null,"service":"helmgress.strippy.80","name":"helmgress.strippy.00","strip_path":true,"preserve_host":true,"regex_priority":0,"updated_at":1600299352,"sources":null,"methods":null,"https_redirect_status_code":426,"hosts":["strippy.example"],"tags":["managed-by-ingress-controller"]}

{"host":"strippy.helmgress.80.svc","id":"33351895-9753-45da-8a16-c87bb514e375","protocol":"http","read_timeout":60000,"tls_verify_depth":null,"port":80,"updated_at":1600299352,"ca_certificates":null,"created_at":1600299352,"connect_timeout":60000,"write_timeout":60000,"name":"helmgress.strippy.80","retries":5,"path":"/anything","tls_verify":null,"tags":["managed-by-ingress-controller"],"client_certificate":null}
```

With a port forward to my test proxy that yields:

```
$ curl -sv "strippy.example:8440/space" --resolve strippy.example:8440:127.0.0.1
* Added strippy.example:8440:127.0.0.1 to DNS cache
* Hostname strippy.example was found in DNS cache
*   Trying 127.0.0.1:8440...
* Connected to strippy.example (127.0.0.1) port 8440 (#0)
> GET /space HTTP/1.1
> Host: strippy.example:8440
> User-Agent: curl/7.72.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 456
< Connection: keep-alive
< Server: gunicorn/19.9.0
< Date: Wed, 16 Sep 2020 23:52:06 GMT
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< X-Kong-Upstream-Latency: 135
< X-Kong-Proxy-Latency: 4
< Via: kong/2.1.0.0-internal-preview-enterprise-edition
< 
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Connection": "keep-alive", 
    "Host": "strippy.example:8440", 
    "Snakeman": "2d457b0f-6dc8-43dd-b050-006987458a1a#1", 
    "User-Agent": "curl/7.72.0", 
    "X-Forwarded-Host": "strippy.example", 
    "X-Forwarded-Prefix": "/space"
  }, 
  "json": null, 
  "method": "GET", 
  "origin": "127.0.0.1", 
  "url": "http://strippy.example/anything"
}
```

Slightly different as it's [httpbin](https://httpbin.org/) output rather than logging plugin output, but in practice the upstream path reported by the logging plugin and `"url": "http://strippy.example/anything"` reported back by httpbin should be equivalent, and it does lack the trailing slash for me.

Would advise checking with Kong proxy 2.1.x and controller 0.10.0 in your environment, though I'm not sure if that would change anything from your initial observation. The 2.1.x Kong proxy routing may differ from 2.0.x--I don't think it should, but it's possible (there were definitely some 1.x to 2.x Kong proxy changes in that area). In any case, we'll want to target the latest versions now available for ongoing work. Not entirely sure what all trailing slash handling changes may have appeared since 0.7 and 1.4, but we'll want to work on top of the current behavior.
