### ISSUE TITLE
Ingress Controller for ClusterIP service type

### ISSUE THREAD

**Issue by jraj002** [Kong/kubernetes-ingress-controller#85]
**Is this a request for help?**:
Yes
**What keywords did you search in Kong Ingress controller issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
gke ingress, clusterip
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kong Ingress controller version**:

**Kubernetes version** (use `kubectl version`):
1.10.5-gke.4

**Environment**:

- **Cloud provider or hardware configuration**: Google Kubernetes Engine
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
I am working through the Kubernetes Ingress Controller setup. I created the ingress but see the following error in GKE console:

Error during sync: error while evaluating the ingress spec: service "default/http-svc" is type "ClusterIP", expected "NodePort" or "LoadBalancer"

Does Kong Ingress Controller not support ClusterIPs?
**What you expected to happen**:
Should not see this error.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by hbagdi** [comment]
Hi @jraj002 

This ingress controller doesn't support ClusterIP service type yet.

ClusterIP is a virtual IP in k8s, which is handled by kube-proxy. Using ClusterIP, will result in Kong being unable to do sticky sessions or other load balancing. It's ideal that your ingress point is aware of all the upstream pods of a service and then load balances between them.

I recommend you use a NodePort service, but could you help me understand your use case better here?

**Comment by adamflynn** [comment]
@hbagdi isn't it possible to get IP's for the upstream pods from the endpoint objects? I believe this is how the nginx ingress controller does discovery of it's upstreams when the service is type ClusterIP.
I've also stumbled across this whilst deploying Kong on GKE. I don't want services exposed outside of the cluster, without being proxied through Kong.

**Comment by hbagdi** [comment]
> @hbagdi isn't it possible to get IP's for the upstream pods from the endpoint objects? I believe this is how the nginx ingress controller does discovery of it's upstreams when the service is type ClusterIP.

I could be wrong but I think that doesn't seem to be the case after a [quick glance at the code](https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/controller/controller.go#L753), also check out #48.

While what you recommend is possible, it might make things confusing for the end user who would expect traffic to be routed via the Virtual IP and kube-proxy but Kong would completely bypass it. Thoughts? 

> I've also stumbled across this whilst deploying Kong on GKE. I don't want services exposed outside of the cluster, without being proxied through Kong.

I'm not sure if I understand you correctly. You do not need to expose your services outside the cluster for Kong to route requests to your services. You could just use `NodePort` Service type and Kong will be your Ingress point for all your requests.

Could you share some more details to help me better understand the problem here?

**Comment by adamflynn** [comment]
> I could be wrong but I think that doesn't seem to be the case after a quick glance at the code, also check out #48.

Looking at this [code](https://github.com/kubernetes/ingress-nginx/blob/332b3ad23d1c72be70830a74ac5b2043a0725ef3/internal/ingress/controller/controller.go#L625) the nginx ingress only uses the service if the service-upstream annotation is set. The docs also explain this [here](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#service-upstream)

> Could you share some more details to help me better understand the problem here?

I have services that I do not want to be accessible outside of the cluster. If I use a NodePort k8s will assign a port on every node of the cluster, enabling access from outside k8s.

The PR you linked to [here](https://github.com/Kong/kubernetes-ingress-controller/pull/48) will satisfy this requirement.

Thanks

**Comment by hbagdi** [comment]
@adamflynn I understand the problem here now and I'm willing to incorporate a change to support the virtual ClusterIP as upstream target. I'll either work on #48 or introduce an annotation to control that.


However, I cannot replicate the original issue posted here by @jraj002.
Is it something that is specific to GKE?

**Comment by jraj002** [comment]
@hbagdi Thanks for your attention to this issue. I believe this might be a GKE issue. Ingress controller in GKE requires the Ingress to point a NodePort service.

**Comment by markmssd** [comment]
Good article on how to solve it: https://support.cloudbees.com/hc/en-us/articles/360019569372-GKE-Warning-when-using-multiple-Ingress-controllers
