### ISSUE TITLE
Cannot pull the image for controller

### ISSUE THREAD

**Issue by NeelabhKher** [Kong/kubernetes-ingress-controller#992]
Failed to pull image "kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:1.0": rpc error: code = Unknown desc = EOF

I have installed the ingress controller on AKS private cluster. I am getting this error and not able to pull the image.
![iMAGE PULL ERROR](https://user-images.githubusercontent.com/75498146/102571332-e5462a00-40ae-11eb-9abd-9924c450643f.jpg)
I am using the a helm chart deployment
 helm install kong/kong --namespace ingress-kong --generate-name --set ingressController.installCRDs=false

**Comment by mflendrich** [comment]
@NeelabhKher,

Most likely your cluster, since it's configured in AKS as private, cannot reach the image registry because network access is blocked.
Please either allow network access to the registries referenced by the kong-proxy deployment, or copy those images over to your private registry and override image names in values.yaml.

If the problem still persists, please reply with kubelet logs.

**Comment by NeelabhKher** [comment]
I will check. But I have installed a lot of images on this cluster from docker and bintray. I think that is not the problem. But let me spawn a public cluster and check.

**Comment by NeelabhKher** [comment]
It is working now on the private cluster. Here is what I did based on the event log that I saw after running the Kubectl describe on the kong pod

1. Update the azure fire wall application rule to allow an additional fqdn*.bintray.com. I previously had the dl.bintray.com and *.bintray.io only. Following are all the rules that helped me to solve the image pull issue.
dl.bintray.com,*.bintray.com,*.bintray.io
Note: dl.bintary might not be needed. I still have that to testing purpose.
2. Here there is an observation that it took a while for the pod to run close to 8-10 mins, not sure but I am checking the logs.
